### ISSUE TITLE
Allow download of contact list as CSV

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#110]
The Contacts page should allow downloading contacts as CSV.
The CSV file should be formatted to be compatible with CSV import files.

The same download feature should also be available from the segment editor.

In order to allow also large contact lists to be downloaded, `Keila.Contacts.stream_project_contacts/2` should be used
with `Plug.Conn.send_chunked/2` and `Plug.Conn.chunk/2`.

**Comment by MagicFab** [comment]
This feature is particularly important to avoid problematic cloud vendor lock-in : you can migrate your lists easily into Keila but can't migrate out once in as is right now - unless you're self-hosting and/or have direct access and knowledge to extract from the database. Data portability is essential to reassure users they have 100% control and ownership of their data - and their email recipients'.

**Comment by satoshinotdead** [comment]
I wonder if there is a good practice as manual workaround in order to export the database.

_All tables from postgres and that's it?_

**Comment by wmnnd** [comment]
This feature is now available in version 0.12.6 :partying_face:

**Comment by MagicFab** [comment]
Awesome ! Thank you :1st_place_medal:
