### ISSUE TITLE
Fix style glitch in campaign settings

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#117]
If the sender name is particularly long, this breaks the layout of the campaign settings modal.

**Comment by ExplorerKut** [comment]
hello @wmnnd by layout breaking do you mean something like this.
![image](https://user-images.githubusercontent.com/53145662/155879088-128b4f71-fe28-432c-9e42-48b7bf64fe86.png)

**Comment by wmnnd** [comment]
@ExplorerKut Oh wow, that actually looks kind of neat :joy: 

What I meant is that the campaign settings modal where you can’t see the buttons anymore if the Sender name + email is too long. I think this could be easily fixed by applying `w-full` to the `select` element:
![Screenshot 2022-02-28 at 05-23-10 Open Source Newsletter Tool · Keila](https://user-images.githubusercontent.com/7488303/155923734-b145b0c9-5dbe-403c-b925-d698ca4da32b.png)

**Comment by ExplorerKut** [comment]
Hey, created a Pull Request for the above issue, I am a beginner so don't know much about how to create a good PR but tried my best. 
https://github.com/pentacent/keila/pull/118/commits/6247b25dc718f88c7fdaa00c11f8c7c13fbba103

**Comment by ExplorerKut** [comment]
Updated the PR.
https://github.com/pentacent/keila/pull/118/commits/84745e4792c76641aa04d0a525e7f6a6167c30cf

**Comment by ExplorerKut** [comment]
Will look through other issues as well, see if I can help.
