### ISSUE TITLE
Using html elements causing session breakdown 

### ISSUE THREAD

**Issue by JDPDO** [pentacent/keila#119]
## What happens?

Using the specific character causing first some kind of session (dead-/live-)lock, then storage of corrupted entity, followed by internal server error (500). (_From future_: HTML enclosures are affected too.)

## How to reproduce

1. Create a new template, and name it as you want.
2. Type the sign ` (U+0060, grave accent) in signature field.
3. Things getting weird :confused:, let's get worse :smiling_imp:: Accept site reload and save the template.
4. Try opening the template causing internal server error.

**Comment by wmnnd** [comment]
Thank you for reporting this issue. I haven’t been able to confirm it yet but I will take a closer look later.

Are you interested in helping create a fix for it?

**Comment by JDPDO** [comment]
Yes, but I started elixir programming only several weeks ago.

**Comment by JDPDO** [comment]
I've done some investigation. My foundings:

The error is caused by [earmark's parser](https://hexdocs.pm/earmark_parser/EarmarkParser.html) trying to parse an unfinished [_Gruber Markdown Text_](https://daringfireball.net/projects/markdown/syntax#backslash). The grave accent (\`) encloses for code formatting. For example complet copy <code>\`this works\`</code> and paste. No errors will occur.

What I do not understand so far is: Why are all other enclosures like \{ and \_ not affected?

**Comment by JDPDO** [comment]
The error goes further than assumed: **All HTML element enclosures trigger an invalid template** the moment only one element added.

Try adding `<div>, <p>, ...` triggers the bug.

**Comment by JDPDO** [comment]
What is if we are adding a function closing all open enclosures before passing text to earmarks parser?

**Comment by JDPDO** [comment]
Investigating deeper:  Not using the rich text editor in campaigns edition triggers the bug too.

**Comment by wmnnd** [comment]
The bug that caused session breakdowns with invalid markup in the signature field has been fixed in #175.
