### ISSUE TITLE
No signature applied to text only campaigns 

### ISSUE THREAD

**Issue by JDPDO** [pentacent/keila#123]
No signature or the unsubscribe-link are send if the campaigns format is _Text only_. The chosen template is ignored.

**Comment by wmnnd** [comment]
Thanks for pointing this out! I’m not quite sure how to best address signatures in the context of plain-text campaigns. Do you have a suggestion for this?

**Comment by JDPDO** [comment]
I thought about that too. My idea would be to mimic the behaviour of _default.html.liquid_ in [the email templates folder](https://github.com/pentacent/keila/tree/1d5b5309f45e0485bba40050d5dd912e7296468d/priv/email_templates). So there would be an _default.txt.liquid_ with `{{main_content}}` and `{{signature_content}}` somewhere.

I'll try to address this in my proposal #125.

**Comment by wmnnd** [comment]
With #175, signatures are now appended to plain-text campaigns.
