### ISSUE TITLE
Possible to duplicate `Template` field in _New Campaign_ view

### ISSUE THREAD

**Issue by JDPDO** [pentacent/keila#124]
## What happens?

It is possible to duplicate the template selector in _New Campaign_ view

## How to reproduce

1. Select _New Campaign_ in sidebar
![grafik](https://user-images.githubusercontent.com/11973633/162675504-374a721a-7721-4f97-a297-46a4cc7a1505.png)
2. Change _Campaign Type_ selector to `Text only`
3. Change it back

Now there are two fields. The last of them is saved to database.

**Comment by wmnnd** [comment]
Thanks for reporting this bug! I’ll take a look asap and deploy a fix for it.

**Comment by wmnnd** [comment]
Thanks for your bug report, @JDPDO! The fix has now been merged into main :partying_face:
