### ISSUE TITLE
`Keila.Mailings.Campaign` struct has obsolete field: `html_body`

### ISSUE THREAD

**Issue by JDPDO** [pentacent/keila#126]
If I see correctly the field `html_body` of campaign is never used.

**Comment by JDPDO** [comment]
Wouldn't it be better if the fields `html_body` and `text_body` are merged. Maybe just `body`? The type of body would be clearly identifiable thanks to `campaign.settings` (`Keila.Mailings.Campaign.Settings`).

**Comment by wmnnd** [comment]
It isn’t so much that the field is obsolete, it’s more that it’s not used *yet*. The original idea behind having both fields would be that there could be campaign types that allow users to change the HTML body and text body independently. E.g. if we introduce a HTML block editor, users still might want to modify the plain text version of their emails.
