### ISSUE TITLE
Single Docker Install Command

### ISSUE THREAD

**Issue by devaayushraj** [pentacent/keila#130]
I feel you need to make a shell command to install the docker up and running with the database
Something like Listmonk.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/84487608/170746375-2c0b027b-9c4b-4517-98ab-9a8d3715a8a4.png">

**Comment by wmnnd** [comment]
Thank you for this suggestion.

If you would like to try Keila, you can give it a try at https://app.keila.io/auth/register.

Piping curl into bash is not really a great pattern, so we won’t be adding that as part of our instructions at this point.
I think the installations instructions are already pretty straightforward – but if you feel that something is unclear, please feel free to reopen this issue.
