### ISSUE TITLE
Catered for Content Creators

### ISSUE THREAD

**Issue by devaayushraj** [pentacent/keila#131]
As a content creator we give free email courses in the beginning of the sign up. Where the subscriber gets a series of mail at certain interval.

**A drip campaign option is a must.**

Subscribers getting a confirmation mail is missing.

We don't need fancy options.
Give us 

1. Drip Campaign 
2. Subscriber Confirmation Mailing
3. Newsletter Manager(Already there I guess) 

With these feature alone you can market to the thousands of creators who are using Convertkit/Any other service. We don't need a lot of features. We need simplicity and reliability. I would request you to check out this once https://listmonk.app/

May be this can be of some help: https://github.com/jonathandion/awesome-emails

Will wait for your response.

**Comment by wmnnd** [comment]
Hey there, thank you for your suggestion!

Email automations are definitely planned for Keila! In fact, they’re already listed on the roadmap on keila.io, but I just noticed that there wasn’t yet a ticket here on GitHub. I’ve now opened a new ticket here: #132
