### ISSUE TITLE
Allow custom data in forms

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#135]
Forms should allow users to configure custom data fields (ideally with validation) to add custom data to new contacts.

The types of fields should include:
- text
- date
- number
- boolean

The validations should include:
- minimum/maximum length
- inclusion in list

It should be possible to mark fields as optional/mandatory and visible/hidden.

**Comment by beeb** [comment]
Having the option to add data to a user depending on which form has been used to subscribe would be very helpful (e.g. different locales are targetted separately, we want to know which locale the user was using when subscribing).

**Comment by wmnnd** [comment]
Implemented in #263
