### ISSUE TITLE
Nil root@localhost

### ISSUE THREAD

**Issue by bryanthen** [pentacent/keila#136]
Hello everyone, 

I deployed Keila (both Keila web and Database) on docker. Configured KEILA_USER and KEILA_PASSWORD on the environment, but it's giving me UI error:

"PASSWORD is incorrect". Although the password is extremely basic, with "randompassword" as string. 

Also, tried to find the root@localhost user and password was a tough journey since it was deployed via Portainer Docker Compose without any logs, hence missed the password generated for the default user. 

Based on https://github.com/pentacent/keila/issues/82, I tried to find the root user on the docker, and it was returning the following result: 

iex(keila@3bdc6f488a4c)3> root=Keila.Auth.find_user_by_email("root@localhost")
nil

Now, I am stucked even further without able to sign in to the dashboard. Kindly assist.

**Comment by wmnnd** [comment]
Did you configure both `KEILA_USER` and `KEILA_PASSWORD` before you first started Keila? Because in case you specified just `KEILA_USER` it would have created a user with your specified email but still set up a random password.

You can also try to get a list of all users: `Keila.Auth.list_users() |> Enum.map(& &1.email)`

**Comment by bryanthen** [comment]
Hi @wmnnd , the result of the list_users() is returning [ ], an empty string. I have inserted KEILA_USER and KEILA_PASSWORD on the docker-compose.yml prior to deployment. Technically it should be made available to the application.

**Comment by bryanthen** [comment]
I think i resolved the problem, finally! What I did was to set a HOME environment variable and redeploy the stack again. Thanks @wmnnd  for the command to ensure that I know what I'm doing.

**Comment by wmnnd** [comment]
Excellent, glad to hear you managed to sort this out! :+1:
