### ISSUE TITLE
Tie forms to projects/segments, perhaps using a hidden field

### ISSUE THREAD

**Issue by MagicFab** [pentacent/keila#140]
I would be useful to tie forms to specific projects and/or segments.

When a new user subscribes, this would make it possible to have them added automatically to a segment or project for immediate use in campaigns.

This could be implemented using a hidden field in the form.

**Comment by wmnnd** [comment]
Thank you for your suggestion @MagicFab! We currently have an open issue at #135 which will allow forms to add custom data to new contacts. The proposal also includes the inclusion of hidden fields, so that should work for the use-case you’re suggesting here as well!
