### ISSUE TITLE
Misconfigured sender leads to undefined behavior and broken stats

### ISSUE THREAD

**Issue by ja2ui0** [pentacent/keila#142]
When Keila has a bad URL (ie: smtp.google.org instead of .com) and I try to send a campaign it hangs on "This campaign is currently being sent out. 0/1" forever and there's nothing showing up in the logs. Also, the campaign cannot be canceled.

**Comment by wmnnd** [comment]
Thanks for reporting this issue. You’re right, if the sender is misconfigured a campaign can currently enter an undefined state.

My recommendation if you’re currently stuck with this would be to clone the campaign and try again with a working sender.

**Comment by wmnnd** [comment]
This problem is fixed in #173 which makes campaigns with broken senders fail quickly.

**Comment by wmnnd** [comment]
Keila 0.11.0 (#173) now quickly fails when an email can't be sent out. In a future version I’ll add an improved retry mechanism.
