### ISSUE TITLE
Add environment variable to disable hCaptcha

### ISSUE THREAD

**Issue by aqua-institut** [pentacent/keila#148]
Hi,

for internal/selfhosted use it would be great to have a environment flag to disable hCaptcha completely (or just disable it if SECRET and SITE_KEY are not set).

Best,
Moritz

**Comment by wmnnd** [comment]
Thank you for your suggestion! Would you like to try and create a PR for this issue?

**Comment by aqua-institut** [comment]
Unfortunately I don't have that deep understanding of Elixir to do it right away. Might check on it in the coming weeks :)

**Comment by wmnnd** [comment]
I will close this for now; if hCaptcha is not configured, it will not have any breaking negative consequences – after all, there’s merely a warning which might actually be desireable.
