### ISSUE TITLE
URL_PORT default seems to be wrong or documentation misleading

### ISSUE THREAD

**Issue by throny** [pentacent/keila#149]
Hi,

according to the official docs the `URL_PORT` should be `80` if `URL_SCHEMA` is set to `http` (which is the default value)
That seems to be not the case if the `PORT` is on `4000` as the mail confirmation for registration appends `:4000` to the URL.

Right now it's required to set the URL_PORT to 80 manually.

Best,
Moritz

**Comment by wmnnd** [comment]
Thanks for pointing this out; are you referring to the log message you get when starting Keila?
That message seems to be indeed incorrect because `URL_PORT` doesn’t default to 80.

**Comment by aqua-institut** [comment]
Hi,
nope, I meant the generated link in the activation mail when running with the defaults (host port 80 to internal 4000, leaving `URL_SCHEMA` and `URL_PORT` unset)

**Comment by black-fake** [comment]
Hi,

same "problem" here with https schema.

After manually setting **URL_PORT** to **443** the creation of links for the subscription form works well but before that there was automatically appended the port **4000** to the URL.

Seems to be the default value, no matter, if **URL_SCHEMA** is set or not

**Comment by wmnnd** [comment]
Thanks for your feedback! I’ve slightly updated the configuration behavior and the relevant documentation:
- If `URL_SCHEMA` is set, `URL_PORT` will default to `443` (i.e. no port is appended)
- If `URL_SCHEMA` is not set, `URL_PORT` defaults to the value of `PORT` which in turn defaults to `4000`.

-> https://www.keila.io/docs/configuration
