### ISSUE TITLE
Add Phoenix.LiveView.HTMLFormatter

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#153]
We should enable the Phoenix HTMLFormatter to ensure consistent formatting in heex templates.
https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.HTMLFormatter.html

**Comment by panoramix360** [comment]
I was planning on doing this one, but I noticed that the HTMLFormatter has a limitation in using Elixir >v13.4

![image](https://user-images.githubusercontent.com/2154092/201555049-f9823a1c-2748-42b0-9990-280330469e91.png)

Do you plan to update Elixir on the project?

**Comment by wmnnd** [comment]
Yes, we should definitely upgrade to Elixir 1.14. Would you like to prepare a PR for that?

**Comment by panoramix360** [comment]
yep, I can upgrade it 🤓

**Comment by panoramix360** [comment]
@wmnnd I'll try to tackle this one now on upgrading Elixir :)

**Comment by panoramix360** [comment]
I'll work on this once we got the #173 merged, it will upgrade Elixir so this will be available to work on.

**Comment by panoramix360** [comment]
@wmnnd I believe you forgot to close this issue :)

**Comment by wmnnd** [comment]
True! Thanks again for implementing this in #214
