### ISSUE TITLE
Add style settings for text alignment in template signature

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#155]
It should be possible to change the alignment of the content of the signature block from center (default) to left or right.

**Comment by wmnnd** [comment]
Sure! In the styles section, we should add another option under "Signature": Text alignment - where users should be able to choose between left, right, center, and justified alignment. And then that settings should be applied to the signature.

**Comment by wmnnd** [comment]
Implemented in 8e8ba55e44a3c153aa7a85d151c7ba17125087f6.

**Comment by panoramix360** [comment]
@wmnnd sorry for not delivering this earlier, I'm still with little time outside work 😢 

I'll look into the issues to try to fix one, it's been a while that I didn't use Elixir 😭
