### ISSUE TITLE
Edit HTML of emails

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [pentacent/keila#161]
The WYSIWYG is great, but we would like to edit the core HTML of the messages. The ability to view & edit the raw HTML in the campaign builder would be a huge benefit.

**Comment by wmnnd** [comment]
The current WYSIWYG editor is based on Markdown, so it’s not possible to edit the HTML because it’s automatically generated from the Markdown markup. I am planning to include HTML campaigns in a future version, though.
