### ISSUE TITLE
The campaign editor is not loading

### ISSUE THREAD

**Issue by nsakibp** [pentacent/keila#162]
The campaign editor is not loading for Markdown or, Text only both options.

Here is the screenshot:
https://paste.pics/JGQEM

**Comment by wmnnd** [comment]
Could you share the output from both the Elixir console and the browser JS console?

**Comment by nsakibp** [comment]
I don't know Elixir
I used docker to install Keila

Here is the browser console output:
https://paste.pics/JGRA0

**Comment by wmnnd** [comment]
It looks like there is something wrong with your server (or remote proxy) configuration and the websocket connection is failing.
