### ISSUE TITLE
Error with docker

### ISSUE THREAD

**Issue by TOH2F** [pentacent/keila#166]
I configured a password in the docker compose file but when connecting the application it does not work

KEILA_USER : "root2@localhost"
KEILA_PASSWORD : "123456789"

Thank you for your help

**Comment by wmnnd** [comment]
Did you set these environment variables before you started Keila for the first time? Otherwise, Keila is just going to create a `root@localhost` with a random password.

**Comment by wmnnd** [comment]
I’m closing this issue for now. If you still need help, please feel free to reach out again, @TOH2F.
