### ISSUE TITLE
Internal Server Error when disabling "Allow embedding as HTML" 

### ISSUE THREAD

**Issue by digitalfredy** [pentacent/keila#167]
Expected:

Disabling _Allow embedding as HTML_ the form should be showed in the proposed URL (eg: https://app.keila.io/forms/random-string) but not showed if embedded from other domain names.

Problem definition:

If I disable _Allow embedding as HTML_ the URL proposed by Keila shows _Internal Server Error_

Tested on Firefox ESR 102.3.0esr (64-bit) on Debian 11

**Comment by wmnnd** [comment]
Hey there, thanks for reporting this issue! I’ve verified it and will fix it asap. In the meantime, I recommend you proceed with leaving the option enabled.

**Comment by wmnnd** [comment]
Thanks again for reporting this, @digitalfredy! I just fixed this issue in e8ed0ac97564cb952cee887086df1800259dbd17 and the update is already live on Managed Keila.
