### ISSUE TITLE
Check handling of email addreses with special characters

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#17]
I just noticed on another project that `gen_smtp`/Swoosh threw errors when using email addresses with special characters.
It needs investigating how Keila can/should handle email addresses such as `äðç@example.com` or `foo@äðç.example.com` if both of these cases are considered even valid email addresses.

**Comment by crova** [comment]
So Keila accepts an email such as `äðç@example.com` and later when trying to deliver a message, Swoosh will complain about this address, is this correct?

If that's the case, we need to enforce whatever rule Swoosh has for email validation, within Keila. Is that the case?

**Comment by wmnnd** [comment]
Actually I haven’t tested this with Keila. This occurred with another project using Swoosh.

Keila only checks that emails contain an `@` character.

So we need to figure out the following:

- Do emails with special characters cause any problems at all?
- If so: Which emails should theoretically be valid? For example, I don’t know if special characters are allowed before the @. But there are internationalized domains with special characters and those are definitely valid email addresses.
- If there is an issue sending to these valid email addresses: How can we mitigate it? It might need fixing in Swoosh or a workaround in Keila.

**Comment by crova** [comment]
All right, thanks for the clarifications.
As for your questions:
* **Do emails with special characters cause any problems at all?** => I'll see if I can make some tests to check this assumption.
* **If so: Which emails should theoretically be valid? For example, I don’t know if special characters are allowed before the @. But there are internationalized domains with special characters and those are definitely valid email addresses.** => Looking at Swoosh code, it would seem that they follow [RFC 822](https://github.com/swoosh/swoosh/blob/main/test/support/RFC822_parser.ex) which I think is the first RFC for mail. This RFC was modified and improved a few times by other RFCs. If I'm not mistaken, the last one would be [RFC 5322](https://www.ietf.org/rfc/rfc5322.txt). In theory, the following regex `/(?=\A.{6,255}\z)(\A([\p{L}0-9]+[\w|\-|\.|\+]*)@((?i-mx:[\p{L}0-9]+([\-\.]{1}[\p{L}0-9]+)*\.[\p{L}]{2,63}))\z)/` is strict enough to, somewhat, abide to RFC 5322 while still being a little flexible. This is the default regex for [truemail gem](https://github.com/truemail-rb/) which I used extensively in previous Ruby projects and always served me well. Validating against this regex, your sample emails would be accepted as being valid, so I don't see why Swoosh/Keila wouldn't be able to support them (at least both cases you presented).
* **If there is an issue sending to these valid email addresses: How can we mitigate it? It might need fixing in Swoosh or a workaround in Keila.** => This one would be easier to answer once it's more clear if we actually have a limitation somewhere right now.

On the matter of what should be valid input (as far as email addresses), I would assume that the easiest path is to stick with any RFC and enforce it within Keila (and making sure that it is accepted by Swoosh).
I could not find on the Swoosh codebase anything related to `email validation` per se (but it was a quick look, so I might have missed something).

**Comment by Jcambass** [comment]
Just to leave my 2cents: 

I'm strongly against validating emails with anything beyond simply checking for an `@`. 
My reasoning is the following:

If Keila needs to know that an email is valid then we should use email confirmation since it's to only way to guarantee that the email is valid in terms of semantics and functionality.

If we only have a dependency like Swoosh that only allows specific formats I would just handle the specific error. That way we don't duplicate validation just for the sake of not getting the errors that we can handle. We're also more flexible if some Swoosh adapters have different validations (100% hypothetical).

**Comment by wmnnd** [comment]
I agree with validating just for the presence of the `@` (which is also what Keila is doing at the moment). 

So what I would like to achieve is to 1) know how Keila behaves with emails that include special characters, 2) where any issues that may arise come from, and 3) consider whether there’s something we can do about it.

**Comment by crova** [comment]
Hello folks,

So, I tested a couple of emails with special chars (`äðç`, `éèëê`, `ûü`) and I can't seem to reproduce any issue for now.
They were all added on a valid email after the `+` sign (e.g.: `valid_email+äðç@gmail.com`) and they were delivered.
I used Gmail SMTP for sending.

I'm not sure how to test this against `domains with special characters (like `something@äðç.com`). If anyone has any suggestion on how to test this I'm all ears.

**Comment by wmnnd** [comment]
It looks like everything is working as expected, thanks for your input @crova :+1:
