### ISSUE TITLE
Support Postmark as an email sender

### ISSUE THREAD

**Issue by aej** [pentacent/keila#176]
Hi 👋 

I was wondering whether there was any appetite to support Postmark as a sender? 

I'm happy to take a stab at implementing this myself since it looks like keila uses [Swoosh](https://hexdocs.pm/swoosh/Swoosh.html) for the email adapters and Swoosh supports Postmark.

Thanks

**Comment by wmnnd** [comment]
Hey there,

thanks for wanting to help out!

Creating new sender adapters in Keila is pretty straighforward. You’re right, we’re using Swoosh, so you just need to write a thin adapter module implementing the `Keila.Mailings.SenderAdapters.Adapter` behaviour and add the UI. I’d be happy to accept a PR!
