### ISSUE TITLE
Image uploads don’t show up when there are no previous uploads

### ISSUE THREAD

**Issue by digitalfredy** [pentacent/keila#186]
I tried to upload a file via markdown editor and I got this window:

![20230201_17h51m28s_grim](https://user-images.githubusercontent.com/1372919/216185251-cfc1e05f-d151-49db-ac42-c6cb6d80b2e6.png)

- If I click *Start Upload* nothing happen
- If I click *OK* it closes the window and nothing happen.

Expected:

Start upload button should upload the file and I guess then I should choose it from the lower section and click in OK to add it.

**Comment by digitalfredy** [comment]
Platform: Firefox 102.3.0esr (Debian Linux 64-bit)

**Comment by wmnnd** [comment]
Hey, thanks for reporting this issue! Image uploads seem to be working fine on my end. Could you try reloading the page and see if the image is showing up after all?

**Comment by digitalfredy** [comment]
Indeed now I can see it.

**Comment by wmnnd** [comment]
I think it’s a bug that images don’t show up when there were 0 images before. I’ll fix it asap!

**Comment by wmnnd** [comment]
Thank you for reporting this! I’ve fixed this now and the fix is already live on keila.io.
