### ISSUE TITLE
Markdown editor: Preview button does not work - inconsistent

### ISSUE THREAD

**Issue by digitalfredy** [pentacent/keila#187]
In the markdown editor:

![20230201_18h12m46s_grim](https://user-images.githubusercontent.com/1372919/216188398-d28aca34-e12d-4f44-9f41-c42c652de626.png)

If I mouseover the eye button  (top-right)  it shows "*Edit plain Markdown*" then I click the eye button and it shows:

![20230201_18h13m10s_grim](https://user-images.githubusercontent.com/1372919/216188556-cdcba8f6-9a37-4cc7-9143-a206f4d0d495.png)

1. It does not work
2. Is not clear what supposed to happen because the editor is WYSIWYG then why a preview?

Platform: Firefox 102.3.0esr (Debian Linux 64-bit)

**Comment by wmnnd** [comment]
Hey, thanks for reporting this! The preview is supposed to show you the email in its entirety, including the footer and background. One reason why it might not be showing correctly could be broken Liquid tags. Do you have any potentially invalid Liquid in your campaign?

**Comment by digitalfredy** [comment]
I realized It works while using the pure Markdown editor, it does not work with the WYSIWYG editor.

I did not changes to Liquid templates  I'm using the SaaS.

**Comment by wmnnd** [comment]
Could you share the link to the campaign where this is happening with me? You can also send it to me via email at hello -at- keila -dot- io.

**Comment by wmnnd** [comment]
The preview button should now always work with the Markdown WYSIWYG editor, even if there is invalid Liquid markup. This was fixed in #175.
