### ISSUE TITLE
[Bug][SaaS]  Edit Campaign: Changing the title wipe the content

### ISSUE THREAD

**Issue by digitalfredy** [pentacent/keila#188]
How to reproduce:

1. Click to create a Campaign
2. Name it "Hello"
3. Remove template content and write `Hello world` instead
4. :thinking: better to change the title then change the name from "Hello" to "Hello world"
5. You will lost all the content you wrote for your campaign :crying_cat_face: 
6. Rename it again as  "Hello", Nothing, you lost your work :cry: 

Expected:

Changing the campaign name should not affect the content.

Platform:

Tested on Firefox 102.3.0esr (Debian Linux 64-bit)

**Comment by wmnnd** [comment]
Thank you for reporting this! I’ve fixed this now and the fix is already live on keila.io.
