### ISSUE TITLE
keila exited with code 139

### ISSUE THREAD

**Issue by Nicolab** [pentacent/keila#190]
Hello,

I try to run keila in local but the keila container doesn't start, I have this message `keila exited with code 139`.
Does this sound familiar?

I use the docker-compose example in ops directory. I have added a `.env` file for the env var in the docker-compose.yml file.

**Comment by wmnnd** [comment]
Could you share the full log output you get when trying to start Keila?

**Comment by wmnnd** [comment]
If this issue continues to persist or if someone else experiences the same problem, please feel free to reopen the issue. For now I’m closing it.
