### ISSUE TITLE
Storage options

### ISSUE THREAD

**Issue by beeb** [pentacent/keila#192]
I would like to deploy keila to railway.app which works fine, but railway doesn't provide persistent storage for docker deployments.
Would there be a way to add support for something like AWS S3 for uploaded user files?

Thanks!

EDIT: I see this was mentioned initially at https://github.com/pentacent/keila/issues/38#issuecomment-796764394
It would be awesome to add support for S3 now ^-^

**Comment by wmnnd** [comment]
Hey, thank you for your suggestion.

There are currently no plans from my side to add other storage options, but the storage system is already designed in a modular way and I’d be happy to review and accept a PR adding S3 support through `ex_aws`.

Would you be interested in helping with that, @beeb?

**Comment by beeb** [comment]
Hey @wmnnd, I've never written a line of Elixir, and I'm currently learning Rust. I fear this leaves me no time to go about a PR unfortunately (although I'm usually happy to do so when I'm able to). Hopefully someone with the skills will read this!

**Comment by wmnnd** [comment]
Then I’m going to close this issue for now. But I’m sure we will get S3 support eventually.

In the meantime you might be able to find a way to locally mount your storage solution. The deployment on keila.io, for example, uses mounted block storage for files. If you want to stick with S3, [S3FS](https://github.com/s3fs-fuse/s3fs-fuse) might be an option for you. Keila doesn’t use any special filesystem-related features like inotify, so it should work without issues.

Anyone who wants to help with S3, please feel free to reopen :smiley:

**Comment by beeb** [comment]
@wmnnd oh intersting, is there a way to derive a new docker image from the official keila one that would include S3FS? Custom dockerfile is possible with railway, but not docker-compose.

**Comment by wmnnd** [comment]
I’m not really familiar with Railway but from what I can see they don’t have any built-in way of mounting block storage or s3 storage. In principle you could of course derive your own Docker file from our official Keila file.

But it might be easier to go with something like a managed Kubernetes solution (e.g. on Scaleway or Digital Ocean) or fly.io which also has support for volumes.

**Comment by bruce** [comment]
@wmnnd I'm happy to take this on if s3 support is still something you'd be interested in including.

I have some experience with ex_aws, so my plan would be add it as an optional dependency to enable an S3-specific storage adapter.
