### ISSUE TITLE
Feature Request: Double confirmation when adding contacts

### ISSUE THREAD

**Issue by kevmodrome** [pentacent/keila#197]
We use a double confirmation flow (user signs up, email is sent out, user clicks link to confirm signing up) when signing up users to our newsletter, Keila doesn't seem to support this out of the box. If it does, I haven't found the setting for it.

Would it be possible to add this feature?

Currently I have to create a segment that checks if a data field is valid and do the confirmation myself which is quite a hassle, and honestly not something I want to keep doing.

**Comment by wmnnd** [comment]
Hey, thank you for your suggestion! This feature is planned for a future Keila version and already tracked at #141!

I’m closing this issue because it’s a duplicate, but if you want to help with the implementation of the feature, let me know!
