### ISSUE TITLE
Tusk is not keila

### ISSUE THREAD

**Issue by Nicd** [pentacent/keila#2]
In the readme it's stated that the word in Finnish for an elephant's tusks is "keila", but I cannot find any source for this being true. Google Translate does think so, I guess because the name of [a fish called cusk or tusk](https://en.wikipedia.org/wiki/Cusk_(fish)) is keila in Finnish. If you translate the plural "tusks", it responds with the correct "syöksyhampaat" ("syöksyhammas" being the singular form).

So the name of this project, if interpreted in Finnish, either means a bowling pin (the most used connotation I reckon, so used that "bowling" is actually "keilaus/keilailu"), a beam ("valokeila" = "beam of light"), or this fish (which probably most don't even know about, I sured didn't before this).

**Comment by wmnnd** [comment]
Kiitos! I’m afraid my knowledge of Finnish is extremely limited, but I’m pretty confident this means *Thank you*, having heard it from Finnish musicians on stage :sweat_smile: 

I will remove the incorrect wording from the README.

**Comment by Nicd** [comment]
Oh I checked, syöksyhammas.io is still free. ;)

Or you could make it bowling themed! Anyway, good luck with your project ja terveisiä Suomesta. :)
