### ISSUE TITLE
Sending doesn't work but no errors

### ISSUE THREAD

**Issue by beeb** [pentacent/keila#201]
Hey there!

I setup keila to run in docker on a small VPS node. I configured the Sender as SMTP with all the information that previously would work (when I was trying self-hosted in docker on my local machine).

However, when sending campaigns now that everything is setup (with domain name and https using caddy reverse proxy), the emails don't go out and I get no useful error to debug.

The logs after I click "Send":

```
13:03:26.424 request_id=F1If1AQP7f8DOe8AAAxR [info] GET /projects/np_weLJnLY5/campaigns/nmc_X4V8agWa/stats
13:03:26.467 request_id=F1If1AQP7f8DOe8AAAxR [info] Sent 200 in 42ms
13:03:26.759 [info] CONNECTED TO Phoenix.LiveView.Socket in 34µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "OmotISxYCRc7BBRPPC94eSUZBBB2LR4et3Jfk0Z_WKP5wp0-lufE5kN-", "_mounts" => "0", "_track_static" => %{"0" => "https://mail.mydomain.net/css/app-18d229c79bc75a395d45a2c773b20a61.css?vsn=d", "1" => "https://mail.mydomain.net/js/app-77bc5d889843ec24dd7206c75e8811ae.js?vsn=d"}, "vsn" => "2.0.0"}
```

In the UI, I see the loading bar (which stays at zero) for a few seconds, then it switches to blank. The sidebar and title are visible, but no content.
The developer console in the browser shows no error.

When visiting the Stats page for this campaign, the page is still blank:

![image](https://user-images.githubusercontent.com/703631/229354760-cfec3c47-239f-41e4-9992-b6935cb97239.png)

Is there any special considerations regarding the firewall? At the moment I only allow SSH and HTTP(S) inbound.

**Comment by wmnnd** [comment]
It looks like there might be a problem with your sender configuration. If you’re using SMTP, maybe it’s a wrong port or an incorrect SSL setting. Keila currently silently fails when there is a sender configuration problem; this is something we will hopefully improve in future versions.

Some VPS might be limiting SMTP ports, so maybe that could be an issue here too.

**Comment by beeb** [comment]
Hey @wmnnd thanks for the reply.

I ruled out a problem with the software firewall by disabling it, and still see the problem. Likewise, there are no problems with the SMTP settings because they were working inside keila when testing locally.
Without logs of what is going wrong it's really hard to debug, hopefully this improves soon!

**Comment by beeb** [comment]
Seems you were right https://www.linode.com/community/questions/19516/cannot-send-email-using-smtp-on-linode#answer-71470

**Comment by wmnnd** [comment]
> Seems you were right https://www.linode.com/community/questions/19516/cannot-send-email-using-smtp-on-linode#answer-71470

Thanks for sharing the solution!
