### ISSUE TITLE
Make it clear how "trial" is limited

### ISSUE THREAD

**Issue by nk9** [pentacent/keila#202]
This product looks great, and I'm very excited to see something disrupting the expensive email newsletter market. Thank you for your work on it!

As someone evaluating this for my use case, there's one important piece of data missing: if I sign up to [try Keila](https://www.keila.io/try), what are the limits to the service before I pay? Contact count, email sends, a certain time period?

This isn't really an issue, I would have put it in the Discussions section of the repo… but it looks like there isn't one. Please let me know if I should send this somewhere else.

**Comment by wmnnd** [comment]
Hey, thanks for your feedback!

The one thing that you currently can’t do on our hosted version of Keila before signing up to a paid plan is sending emails. I’m currently working on an improved onboarding experience (#106) and I’ll consider making this clearer then.
