### ISSUE TITLE
SNS Topics / Webhook Endpoints

### ISSUE THREAD

**Issue by jgardner-qha** [pentacent/keila#220]
I'm trying to evaluate Keila on my own server and using Amazon SES as a Sender, which is working great. Looking through the documentation, however, I cannot seem to find anything regarding the SNS topic webhooks / endpoints for handling bounces, complaints, etc. through Amazon SES and SNS. There's quite a bit of code that hints at support for SNS topics. Can anybody tell me which SNS topics Keila supports, and what the endpoints are?

**Comment by wmnnd** [comment]
Hey, thanks for asking this question! The API endpoint for notifications from SES is `/api/webhooks/senders/ses`.

**Comment by jgardner-qha** [comment]
Thanks! That was the missing piece for me. Now it seems to be working perfectly!

**Comment by energywave** [comment]
Can you please specify how to configure SNS to work with Keila webhook? I'm pretty new to Amazon SES and it's not so straightforward to understand. I configured my domain, DNS, etc. I'm sending correctly but the first question that arise is: what events should I send to SNS? In particular opening and clicks? I think now as I believe they're managed by Keila but... I'm not sure.
A help page about configuring Amazon SES would be of enourmous help to help users in first configuration like me.
...but in the meanwhile can you give me some hints please?

**Comment by Krisseck** [comment]
@energywave I'm also new to Amazon SES, but this is (roughly) how I set it up.

- Go to Amazon SES dashboard
- Go to "Set up" page
- There should be task "Monitor email sending", click "Add destination"
- Add new destination, I selected everything in "Sending and delivery"
- Create a new SNS topic or use existing topic
- Go to SNS topics page
- Select the topic you just made / used
- Create a new subscription
- Protocol: HTTPS
- Endpoint: `[your-keila-baseurl]/api/webhooks/senders/ses`
- Click Create

That should be everything. Check the logs in your Keila instance that it communicates correctly, for example I saw this:

```
2026-04-03T09:52:01.446 request_id=XYZ [info] POST /api/webhooks/senders/ses
2026-04-03T09:52:01.683 request_id=XYZ [info] Subscribed to SNS topic arn:aws:sns:eu-north-1:ABCDEF
2026-04-03T09:52:01.683 request_id=XYZ [info] Sent 200 in 236ms
```

**Comment by energywave** [comment]
Thank you so much for your effort to explain! In the meantime I managed to get it to work and already sent some campaigns.
I'll try to compare with my setup to post it here to compare with your setup, hoping that this will be a base for @wmnnd to add some info about how to setup Amazon SES and how to configure it as a help for new users.

**Comment by wmnnd** [comment]
Hey @Krisseck, thanks for the step-by-step instructions! If you like, you could add a new docs page here:
https://github.com/pentacent/keila-web/tree/main/src/content/docs/en!
