### ISSUE TITLE
Only SES is supported?

### ISSUE THREAD

**Issue by zigomi** [pentacent/keila#221]
It doesn't support anything beyond SES? 

What if I wanted to use it with my own email server? Or with any other external one except SES?

**Comment by wmnnd** [comment]
Keila supports SMTP, AWS SES, Mailgun, Postmark, Sendgrid, and Sendinblue to send emails. So if you want to use your own email server, just use SMTP. You can even use your email server with our managed Keila at [keila.io](https://app.keila.io/auth/register) :smiley: 

The thing that is currently only supported by SES indeed is the handling of bounces and spam complaints.
