### ISSUE TITLE
Keila vs ListMonk?

### ISSUE THREAD

**Issue by jontstaz** [pentacent/keila#222]
Hi all,

I recently stumbled across Keila not long after finally making my mind up to use ListMonk for a new project of mine. Now I'm trying to work out what better suits me out of Keila and ListMonk. They both seem to have APIs for all operations which is important. Can you import existing HTML email templates in Keila or do you have to make your own within the Keila platform? And otherwise for those that are familiar with both, how do the 2 platforms compare to each other?

Thanks in advance.

**Comment by wmnnd** [comment]
Hey, thank you for your question. I am personally not super familiar with ListMonk, but as I understand it they don’t really have the ambition to do anything beyond list managing. Keila, on the other hand, also lets you design your campaigns with a WYSIWYG editor and aims to add some more advanced features.

You can’t currently import full custom HTML templates into Keila. Keila currently has three campaign modes:
- Plain text
- Markdown: You write your email in Markdown (or in our Markdown WYSIWYG editor) and Keila includes the rendered Markdown + a plain text version. You can also insert HTML in your Markdown campaigns.
- Block editor: You create your email in our rich WYSIWYG block editor. Custom HTML is not currently supported here.

For Markdown and Block campaigns, you can design your template (i.e. adjust colors, fonts, etc) in the Keila Template Editor.
