### ISSUE TITLE
Feature request: Ability to add email attachment in campaign

### ISSUE THREAD

**Issue by JohanBraeken** [pentacent/keila#226]
Campaigns are centered around viewable email content.
In some use cases, additional content needs to be distributed in the form of an email attachment.
This is currently not possible with Keila.

This feature request is to have the ability to upload a file, that can be sent as email attachment in a campaign.

**Comment by wmnnd** [comment]
Hey there, thanks for suggesting this! Email attachments are currently not on our roadmap, so I’ll be closing the issue for now. My recommendation would be to host files externally and link them instead; this is generally also better for email deliverability.

But also feel free if you’d like to take a stab at building it yourself and create a PR or to reach out if you’d like to sponsor this particular feature :slightly_smiling_face:
