### ISSUE TITLE
Possible conflict in MAILER environment variables

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila#23]
The [setup guide](https://keila.io/docs/configuration) mentions `MAILER_HOST` and `MAILER_USER`, while the configuration seems to be searching for `MAILER_SMTP_HOST` and `MAILER_SMTP_USER` - see screenshot below.

@wmnnd happy to provide a fix/correct the docs myself if this turns out to be the case!

<img width="708" alt="Screenshot 2021-02-22 at 19 46 17" src="https://user-images.githubusercontent.com/16822008/108780238-05d3aa00-7560-11eb-9b47-0779d7d71228.png">

**Comment by wmnnd** [comment]
You’re right!

Here is the offending incorrect doc (in the keila-web repository):
https://github.com/pentacent/keila-web/blob/3b13594db111920dedaf1e01062211e92752c3ff/content/docs/configuration.md

If you fix it over there, I’ll merge it right away 🙏.
