### ISSUE TITLE
Can Keila be for a newsletter?

### ISSUE THREAD

**Issue by ally9335** [pentacent/keila#231]
I've launched Keila locally. However, I haven't looked around extensively.

Does it support the functionality of a newsletter?

  * ever changing list of the subscribers
  * sending a newsletter with a certain interval, let's say, once in a week, 2 weeks or a month - any option
  * or at least on the certain dates which I'd choose manually
  * and then actually sending out an email to the list, automaticly
  * preparing and scheduling a new email-newsletter for a certain date, for the future

**Comment by wmnnd** [comment]
Hey there, yes, these are all things Keila can do, including scheduling a campaign for a later date!

Btw, if you don’ŧ want to run your own instance, you can also give our managed version a try: https://www.keila.io/try
If you have any further questions, please don’t hesitate to ask!
