### ISSUE TITLE
Suggested Enhancement / Bug fix for EU users: MailGun EU Zone

### ISSUE THREAD

**Issue by harryfear** [pentacent/keila#233]
MailGun implementation needs US/EU switch so we can target EU servers if the MG domain is configured to reside in the EU.

**Comment by zigomi** [comment]
@harryfear what'll happen if you continue to send emails the way you always have done?

**Comment by harryfear** [comment]
Emails won't send because Kaila assumes a web API endpoint that doesn't exist for the EU zone.

https://www.mailgun.com/blog/product/we-have-a-new-region-in-europe-yall/

"All API calls referenced in our documentation start with a base URL. Mailgun allows the ability to send and receive email in either our US region or our EU region."

https://documentation.mailgun.com/en/latest/api-intro.html#base-url-1

**Comment by wmnnd** [comment]
Hey @harryfear, thanks for reporting this! I’ve just implemented a switch between the EU and US API endpoints and it will be included in the next release.

![Screenshot 2024-02-10 at 09-40-42 Edit Sender Test Mailgun Base · Keila](https://github.com/pentacent/keila/assets/7488303/d4ea870b-b938-4d59-a924-6b6ee9775e26)
