### ISSUE TITLE
Plain-text campaign shows Markdown signature

### ISSUE THREAD

**Issue by jnm** [pentacent/keila#236]
Hello, hopefully this is the correct place to post inquiries about the https://app.keila.io/ hosted service :blush: 

I noticed that when sending a plain-text campaign, a non-editable and non-removable Markdown signature / footer is included. It looks like this, for example:
![image](https://github.com/pentacent/keila/assets/2085013/ca191f44-74ae-4725-81fc-4d44bf121fb1)

As an item for the wish list: it'd be nice to make this more plain-text friendly. The wording is a bit challenging, since we can't necessarily say "click" for the unsubscribe link, but maybe something like this would work?
```text
To unsubscribe, please follow this link: https://app.keila.io/unsubscribe/etc/etc
Powered by Keila.io open-source newsletters
```

[A comment](https://github.com/pentacent/keila/issues/123#issuecomment-1095357236) on #123 seems to imply that the user should be able to customize the signature, which would be great, but I didn't see a way to do that on the Keila hosted service.

Thank you!

**Comment by wmnnd** [comment]
Hey @jnm, thank you for pointing this out! I think the easiest solution would be to let users select a template for their plain text campaigns because that’s how you can define a signature for non-plain-text campaigns.

**Comment by wmnnd** [comment]
I’ve now added a new default plain-text signature:

```
Unsubscribe:
{{ unsubscribe_link }}

This newsletter is powered by Keila: https://www.keila.io
```

Once the refactoring of the template system (#355) is done, it should become possible to customize the signature.
