### ISSUE TITLE
add searching of contacts

### ISSUE THREAD

**Issue by lukaprincic** [pentacent/keila#244]
if you have many contacts, search is essential. currently it is very hard to navigate something like more than 200 contacts.

**Comment by wmnnd** [comment]
Hey @lukaprincic, thanks for suggesting this!

Searching and sorting of contacts was implemented in 288e008 and is now available on app.keila.io and will be included in the next release :partying_face: 

![Screenshot 2024-01-04 at 10-27-07 Contacts · Keila](https://github.com/pentacent/keila/assets/7488303/1c8b842a-bc03-4ac8-82ea-8f8276ed3e37)
