### ISSUE TITLE
bug: creating an image-link does not work in markdown

### ISSUE THREAD

**Issue by lukaprincic** [pentacent/keila#245]
in markdown editor - both rich text and plain markdown code - creating a link from an image does not create a clickable image.

for example:

something like:

```
[![](https://static.keilausercontent.com/efaad4f1-5896-4d69-b469-1d2628badc1b.png)](https://www.facebook.com/events/1024564368594210/ "Major Arcana 5 facebook event")
```

does not work.

the image is displayed but it is not clickable.

**Comment by wmnnd** [comment]
Thanks for reporting this issue! I’ve fixed it now and the fixed version is already available on app.keila.io!
