### ISSUE TITLE
API - contact status is not returned

### ISSUE THREAD

**Issue by VZsI** [pentacent/keila#251]
api/v1/contacts?paginate[page]=0&paginate[page_size]=50

contact's status is not returned:

    {
      "data": null,
      "id": "xxxxxxx",
      "inserted_at": "2023-10-12T17:34:31Z",
      "updated_at": "2023-10-12T17:34:31Z",
      "email": "xxxxxxxxx@gmail.com",
      "first_name": "xxxxxx",
      "last_name": "xxxxxx"
    },
    
Version 0.13.0

**Comment by wmnnd** [comment]
Thank you for reporting this bug! I’ve just fixed it and published Keila 0.13.1 which includes this fix :+1:

**Comment by VZsI** [comment]
Thanks!!!
