### ISSUE TITLE
Contact import CSV - Status ignored

### ISSUE THREAD

**Issue by VZsI** [pentacent/keila#253]
When importing a previously exported and edited contacts, and "Replace duplicates" is selected, the status of existing contacts update to "active" regardless of the statuses in the imported CSV.

So all unsubcribed contacts become active again.

**Comment by wmnnd** [comment]
Thank you for reporting this!

I’ve just fixed this issue on main. From now on, if the `status` column is present, only contacts marked as `active` are imported. All other contacts are discarded. I’ve already deployed this on managed Keila and it’s going to be part of the next release.

**Comment by VZsI** [comment]
Great! Thanks!
