### ISSUE TITLE
improve image/media uploads and managment

### ISSUE THREAD

**Issue by lukaprincic** [pentacent/keila#255]
Currently there's no way to upload images when using the markdown editor without the 'rich text editor'. 

When using the rich text editor and uploading/attaching images, the uploader and media manager is extremely basic and a bit clunky. Kudos for it being very fast, but it needs some more love in terms of UI.

Perhaps there could be a separate media manager where one could upload everything and then a way where in non-rich markdown editor entries from media repo could be added in a simple way.

**Comment by wmnnd** [comment]
Hey @lukaprincic, thank you for your feedback! Would you want to have the media manager simply paste the Markdown code for including an image when working without the rich editor?

**Comment by wmnnd** [comment]
Almost done :partying_face: 
![Screencast from 17 12 2023 22_45_40](https://github.com/pentacent/keila/assets/7488303/1fa2fc97-b464-4020-ab8a-d01656c5d5d4)

**Comment by lukaprincic** [comment]
i guess paste is most intuitive.

**Comment by wmnnd** [comment]
@lukaprincic Could you elaborate what you mean by that exactly?

**Comment by lukaprincic** [comment]
> @lukaprincic Could you elaborate what you mean by that exactly?

apologies for vagueness.

how you did it in the screenshot above seems best. after uploading to a mini media manager, and filling out additional fields, by pressing ok, the manager inserts the markdown back to the md editor.

alternative would be to have a button in media manager that would copy the link to the media to users clipboard for later pasting. but i think the way it is being implemented now (according to your animation) seems the best.

**Comment by wmnnd** [comment]
This was already implemented a while back when I added the media insert buttons to the plain markdown editor, so I’m closing the issue.
