### ISSUE TITLE
No user management visible

### ISSUE THREAD

**Issue by s00500** [pentacent/keila#256]
First of all: Awesome project!!!!

Was straight forward to setup

I am using a selfhosted instance, and if I open the user section I only see my admin user. Is this a limitation or am I doing something wrong ?

Greetings

**Comment by wmnnd** [comment]
Did you register another use? There is currently no interface for creating other accounts as an admin.

**Comment by s00500** [comment]
Ah perfect, that was the answer I was looking for, works like a charm if done via the signup form, thanks :-)
