### ISSUE TITLE
Delete all contacts - "Delete All" Button

### ISSUE THREAD

**Issue by VZsI** [pentacent/keila#258]
I have ~15K contacts.

A "**Delete All**" button is needed.

I need to syncronize Keila with my master table regularly.

**Comment by wmnnd** [comment]
I wouldn’t recommend regularly deleting all contacts. This would also delete the information of users who have unsubscribed and I don’t think that’s desirable. For now, I would recommend using the API to synchronize your databases until we implement #115 which will make tracking contacts that are managed in an external database easier.

Btw, if you need help with the API implementation, feel free to reach out via email :blush:
