### ISSUE TITLE
Internal Server when clicking "Delete selected contacts" without having contacts selected.

### ISSUE THREAD

**Issue by CSDUMMI** [pentacent/keila#260]
I was on the contacts page of a project and clicked the button "Delete selected" before selecting the contacts I wanted to remove. This lead to a text-only "Internal Server Error" page.

The controller of the delete action should probably check if any contacts are selected and fail gracefully and the UI could probably be changed to make the "Delete selected" button unclickable unless at least one contact was selected.

**Comment by wmnnd** [comment]
Thank you for reporting this, I can confirm this is a bug and I’ll fix it soon.

**Comment by wmnnd** [comment]
This has now been fixed, thanks for reporting this @CSDUMMI.
