### ISSUE TITLE
How to resume sending?

### ISSUE THREAD

**Issue by KLISCHE-HW** [pentacent/keila#273]
Hi folks!

I created a newsletter with 2100 contacts.

slow sendrate: 35 msg/h
Keila version: 0.14.0

Everything worked fine, until it reached 438 delivered mails.
The sending process was stopped and now I want to resume the sending process or find out which contacts was successfull sent and retry to send a different campaign.

Unfortually I cant find how to resume sending or which contacts were executed.

**Comment by wmnnd** [comment]
There's currently no way to do this from the UI, but you can take a look at the `mailings_recipients` table (filter by `campaign_id`) to see which emails were sent and which ones weren't. Also, unless sending the emails actually failed, the sending process should automatically continue. You might get some insight from the `oban_jobs` table to see if some sending jobs are still pending and about to be retried.

**Comment by KLISCHE-HW** [comment]
Now I was able to import the contacs with a tag and added a segment with that tag to send the remaining unsent emails.

Thank you very much for your help!

**Comment by wmnnd** [comment]
I'm glad this worked! If you saw anything unusual in the logs or in the recipients/jobs table, please feel free to share, then I can try to take a closer look 😊
