### ISSUE TITLE
Introduce PurgeCSS for Tailwind

### ISSUE THREAD

**Issue by pascalwengerter** [pentacent/keila#28]
When checking if Webpack works on #26 I realized that the `../css/app.ass/` is ~4MB in size. This is due to Tailwind creating a lot of helper classes and can be optimized for production use via PurgeCSS.

Here's a [guide](https://pragmaticstudio.com/tutorials/adding-tailwind-css-to-phoenix), happy to take care of this eventually (unless someone else is quicker than me 🤓 )

**Comment by wmnnd** [comment]
Will you do it if I assign this issue to you? :wink:

**Comment by pascalwengerter** [comment]
> Will you do it if I assign this issue to you? 😉
> 
> P.S.: And to be super clear: The CSS should not be 4 MB so this needs to be fixed.

I will! Haha

At this stage of the project the 4 MB don't matter too much I guess (few users, caching etc), but definitely a quick win in my eyes! Maybe we can also shed off some more KBs with the fonts, let's see.
