### ISSUE TITLE
How to filter contacts by custom data field

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#280]
Hello, I try to filter contacts by custom data using the `/api/v1/contacts` endpoint. I have a `contactType` custom data field.

I tried the following filter queries:
```
{"contactType":{"$like":"%"}}
{"data.contactType":{"$like":"%"}}
{"data": {"contactType":{"$like":"%"}}}
{"$and": {"data": {{"contactType":{"$like":"%"}}}}
```

But for every of the above queries I get an `Internal server error`.

**Comment by wmnnd** [comment]
I think this was answered by my comment in #279 :blush: 

I’ll take a look though if there are cases where a valid filter might still make the UI break.
