### ISSUE TITLE
Allow creating users from administer users page

### ISSUE THREAD

**Issue by doobry-systemli** [pentacent/keila#284]
Trying out the official keila Docker image, I didn't find a way to add new users when logged in as root user. The web interface only lists the sole user, without any options to add/edit/delete users:

![grafik](https://github.com/pentacent/keila/assets/25278864/e9a8cd4d-2684-4f23-9e88-72ff57f5bd5c)

Do I miss something? Or is user management somehow disabled in the official Docker image?

**Comment by wmnnd** [comment]
Hey, thank you for your question! You can’t currently create new users on this page. You can register new users at `/auth/register`

**Comment by doobry-systemli** [comment]
Oh, I see. So there is no option to disable user registration but at the same time manage users as the admin user?

**Comment by doobry-systemli** [comment]
We're thinking about running a  keila instance for activist projects, but open registration is no option for us. So we'd envision a setup where our admin user can add new users manually on request and these users can maintain their campaigns and contact sets.

**Comment by wmnnd** [comment]
You can quite easily accomplish this via the console at the moment before this feature will eventually be added. 

Open the console like this on the container:

`/opt/app/bin/keila remote`

Then execute the following command:

```elixir
Keila.Auth.create_user(%{email: "user@example.com", password: "secure-password-123"})
```

**Comment by wmnnd** [comment]
I’ve updated the title of the issue and added it to the roadmap. We should add a feature to create new users from the admin page.

**Comment by pmareke** [comment]
Hi @wmnnd I would like to give it a try.

The change should be enable a button to create users, right? Do you want to list/edit them as well?

Do you have any sketch about the UI?

Thanks!

**Comment by wmnnd** [comment]
This has now been implemented by @pmareke! 🥳
