### ISSUE TITLE
reduce log level to error via env variable

### ISSUE THREAD

**Issue by tcurdt** [pentacent/keila#289]
When running the docker image I would like to avoid logging the simple http requests.
I was hoping I could just set a ENV variable and reduce logging from INFO to ERROR - but I couldn't find any docs about this yet.

I bet there is a way?

**Comment by wmnnd** [comment]
Thanks you for suggesting this! I’ll add this to our roadmap.

**Comment by kevinam99** [comment]
Is anyone doing this? I can take this up if it is available

**Comment by kevinam99** [comment]
Opened the PR here https://github.com/pentacent/keila/pull/360 
Let me know if it is okay :)
