### ISSUE TITLE
Missing bounce contacts

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#291]
Hello,

I have a segment in Keila containing 18 contacts. One of them is an invalid E-Mail address (asdf@sldvcrtgbgzujmdompie.de).

After waiting for 30 minutes, I see no new "undeliverable" contact in the UI and when querying the API with the contact ID, it still is in "status:active" state.

Also no sign of a bounce in the campaign stats.

It looks like a bug to me, can someone confirm?

**Comment by wmnnd** [comment]
An incorrect domain is usually classified as a soft bounce by SES because it’s hard to tell if a domain is permanently unavailable for receiving emails or if there’s a temporary connectivity issue.

**Comment by wmnnd** [comment]
One more thing: SES will retry emails that give a network error for about a day before registering it as a bounce.
