### ISSUE TITLE
Segment filter memorization issue

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#292]
When I create a new segment filter using the "ends with" widget and return to the page after saving. I see the "starts with" filter is active, although the query json shows "ends with" content:

![Screenshot 2024-05-13 at 10-18-20](https://github.com/pentacent/keila/assets/706491/181bd9fe-393f-4bdf-ae18-325e8c07b3ed)

This can be fixed by selecting "ends with" again, but becomes more cumbersome with multiple conditions.

I expect to see the previously saved state of the conditions when returning to the segment page and match the json query.

**Comment by wmnnd** [comment]
Thank you for reporting this! I’ve fixed this bug on `main` and the fix will be included in the next release.
