### ISSUE TITLE
Custom data usage question

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#296]
Hello, I need to send our customers individual video suggestions. Everything what is needed for this, I have put into custom data. 
After campaign sent I see the following missing fields in layout images:

![screeny](https://github.com/pentacent/keila/assets/706491/3e75d708-f8f3-4ebe-8180-076c814769ba)

I have done this using the block editor and 1-1-1 layout. Inside each column I have put an image using the custom data for the photo, the title and the alt-text. Can I fix this or is it a missing replacement from Keila?

Best regards

**Comment by wmnnd** [comment]
Hey, thanks for reporting this. I actually came across this a couple of days ago and I’m looking into how to fix it :blush:

**Comment by wmnnd** [comment]
Now fixed on main :rocket:

**Comment by dompie** [comment]
Thanks for the fast fix. When will be a new docker version released? We use only the docker container.

**Comment by wmnnd** [comment]
0.14.6 is out now :blush:
