### ISSUE TITLE
Custom data links for images

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#297]
Hello,

some issues have been fixed with ticket #296 when using custom data in Block mode. Nevertheless a part of my newsletter looks now like this:

![screeny2](https://github.com/pentacent/keila/assets/706491/06ad30d0-b6bd-485f-9927-593de084ab1f)

### person1-alt
This is a single image inserted. I used `{{contact.data.person1.previewPhotoUrl}}` as image URL. The alt text was hardcoded just `person1-alt`. Image was not linked and no caption added. The e-mail source looks like: `[...]<img =src=3D"{{contact.data.person1.previewPhotoUrl}}"[...]`

### video2-alt
This time I put image information from custom data inside a block's left column (similar to person1-alt). Not linked, no caption. In the source this looks like: `[...]<img =src=3D"{{contact.data.video2.previewPhotoUrl}}"[...]`

### video3-alt
This is an image (similar to pervious images) but this time I used caption and linked it (hard coded, not from custom data). In the source of the e-mail I still see the following src for the image: `[...]<img =src=3D"{{contact.data.video3.previewPhotoUrl}}" [...]`

So no matter where/how the image was used, custom data is not resolved for image URLs. Can this also be fixed?

**Comment by wmnnd** [comment]
Thanks for reporting this! This should now be resolved with 2f8837185c2717f1c1a2af6fd1bfaaf26a6016a9. 0.14.7 is building right now :blush:
