### ISSUE TITLE
docs: 1-click installer for AWS

### ISSUE THREAD

**Issue by AlaShibanAtKlo** [pentacent/keila#298]
Hey friends! We're big fans of Keila and recently added support for installing it on AWS with an easy installer. It's a free tool we put together. Would be amazing if you guys would be up for linking it on the [installation page](https://www.keila.io/docs/installation)!

This is the Keila page: https://klo.dev/stacksnap/apps/keila/

**Comment by wmnnd** [comment]
Thank you for creating this!

I won’t link it on the Keila website for now because I don’t think endorsing a particular hosting solution would be beneficial to the Keila project at the moment.
