### ISSUE TITLE
Uploaded images vanished after docker update

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#299]
Hello,

we are running Keila as docker container (official image). After updating our container (with `docker compose pull && docker compose stop &&  docker compose up -d --build` ) the previously uploaded images are missing in Keila (and sent E-Mails), but still have entries when selecting an image (see screenshot). New uploads are working perfect (first both top images). Everything else stayed in place after update.

![screeny](https://github.com/pentacent/keila/assets/706491/a1dc460f-004b-4eeb-8194-7f1e727c6142)

My admin says he followed the Keila docs as good as possible. How to find out if my admin made a mistake on setup or if this is a Keila issue? I don't want the assets to dissapear on the next update again.

Maybe we should use another command for the updating the docker container?

Our docker-compose.yaml looks like:
```docker-compose.yaml
version: '3'

services:
  keila:
    image: pentacent/keila
    user: 1002:1002
    restart: always
    ports:
      - "80:4000"
    environment:
		[...]
    volumes:
      - /home/user1/docker/keila/data/uploads:/uploads
    depends_on:
      - db

  db:
    image: postgres:latest
    user: 1002:1002
    restart: always
    environment:
		[...]
    volumes:
      - /home/user1/docker/keila/data/db:/data/postgres

```

**Comment by wmnnd** [comment]
Did you set `USER_CONTENT_DIR` to `/uploads`? It defaults to `./uploads` - so if the path wasn't configured, images would have been stored in the container instead of in the volume.

**Comment by dompie** [comment]
Not it's `/uploads`

Thanks!
