### ISSUE TITLE
How to set block content of campaign by REST API

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#300]
I need to set the content of a block editor campaign. After having a look in the DB, it seems like the `json_body` column stores the block editor content.

I have seen a `text_body` property to fill when using the REST API for a text campaign.
I have seen a `html_boy` property to fill when using the REST API for a markdown campaign.
But I can't use (and find) neither `json_body` nor `block_body` to use on the REST API.

Is there maybe another way to set the content of a block campaign?

Cheers

**Comment by wmnnd** [comment]
I’ve now added `json_body` and `type: "block"` to the Campaign API.
