### ISSUE TITLE
Change double-opt-in text

### ISSUE THREAD

**Issue by aruator** [pentacent/keila#301]
Hi is it somehow possible to change(translate) the Text apearing after submitting the subscription form with Double-Opt-In:

![Keila-Image](https://github.com/pentacent/keila/assets/78870206/01c36218-0f22-43df-b6e1-96b857f8f9a4)

 this is the last thing which prevents us from using keila.

**Comment by wmnnd** [comment]
Hey there, thank you for reporting this a while back. This should have been fixed in v0.14.19. Please feel free to reopen if the translation still doesn’t show.
