### ISSUE TITLE
The Try link in README is 404

### ISSUE THREAD

**Issue by adamshand** [pentacent/keila#304]
Clicking on the try link in the projects main README takes me to a 404 page.

> You can give a hosted version of Keila a try at [keila.io/try](https://www.keila.io/try).

<img width="417" alt="image" src="https://github.com/pentacent/keila/assets/130651/4c7c2c96-2b70-48b9-87ab-d8296d85bb5c">

**Comment by wmnnd** [comment]
Thank you for spotting this! The links have changed with the relaunch of our website and I’ve adjusted the README now.
