### ISSUE TITLE
How to cancel a scheduled campaign?

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#305]
Currently, I see no way how to cancel a scheduled campaign (e.g. because of a typo or wrongly selected date). Instead I see only the following screen:
![Screenshot 2024-06-25 at 08-57-08 Open Source Newsletter Tool · Keila](https://github.com/pentacent/keila/assets/706491/4fbb7173-a314-4c43-b90f-1baf1d7b62d8)

**Comment by wmnnd** [comment]
A scheduled campaign can still be canceled until five minutes before it's about to be delivered. Once delivery has begun, a campaign can no longer be canceled.

**Comment by dompie** [comment]
I have scheduled the campaign to be sent on 31.12.2024 and I can't cancel neither on the "Stats" page nor on the campaigns list.
![Screenshot 2024-06-25 at 10-15-28 Open Source Newsletter Tool · Keila](https://github.com/pentacent/keila/assets/706491/761a22ab-0efb-457a-8bdd-759033e6d7da)
![Screenshot 2024-06-25 at 10-15-20 Kampagnen · Keila](https://github.com/pentacent/keila/assets/706491/4994dca8-6784-453f-87c6-3c05a9ddb46a)

**Comment by dompie** [comment]
I mixed up campaigns. All good, sorry.
