### ISSUE TITLE
Allow line breaks in pull quotes

### ISSUE THREAD

**Issue by madskjeldgaard** [pentacent/keila#308]
Hi

This is a niche feature request, but still: It would be nice to allow the markdown rendering of a pull quote with manual line breaks.

This would allow quoting poems more easily. Right now this:
```
> This is 
> a poem
```

Becomes `This is a poem`

But in some flavours of markdown you can do this:
```
> This is <br>
> a poem <br>
```
And it becomes

```
This is
a poem
```
in the quote. 

That would be lovely feature for people quoting poetry in their newsletters (me, hehe).

Thanks :)

**Comment by wmnnd** [comment]
Hey, thanks for your question! You can alrady create a line break with two spaces at the end of a line.

````
> This is  
> A poem
```

![image](https://github.com/pentacent/keila/assets/7488303/0ac78184-0c17-4e32-9a0c-c982996379d9)

**Comment by madskjeldgaard** [comment]
Great ! Thanks !
