### ISSUE TITLE
DB connection timeout on scheduled campaign send

### ISSUE THREAD

**Issue by dompie** [pentacent/keila#317]
```
09:00:15.334 [error] Postgrex.Protocol (#PID<0.2549.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.843323.0> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.843323.0> was at location:

    (stdlib 5.2.3) gen.erl:259: :gen.do_call/4
    (elixir 1.15.8) lib/gen_server.ex:1071: GenServer.call/3
    (keila 0.14.10) lib/keila/contacts/schemas/contact.ex:2: Keila.Contacts.Contact.Id.encode/1
    (ecto 3.10.1) lib/ecto/type.ex:904: Ecto.Type.process_loaders/3
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:411: Ecto.Repo.Queryable.struct_load!/6
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:243: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
    (elixir 1.15.8) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
    (elixir 1.15.8) lib/enum.ex:4830: Enumerable.List.reduce/3

09:00:15.591 [error] Task #PID<0.843323.0> started from #PID<0.843321.0> terminating
** (DBConnection.ConnectionError) connection is closed because of an error, disconnect or timeout
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:803: Ecto.Adapters.SQL.insert_all/9
    (ecto 3.10.1) lib/ecto/repo/schema.ex:59: Ecto.Repo.Schema.do_insert_all/7
    (keila 0.14.10) lib/keila/mailings/mailings.ex:395: Keila.Mailings.insert_recipients/2
    (elixir 1.15.8) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
    (elixir 1.15.8) lib/stream.ex:1816: anonymous fn/3 in Enumerable.Stream.reduce/3
    (elixir 1.15.8) lib/stream.ex:273: anonymous fn/4 in Stream.chunk_while_fun/2
    (elixir 1.15.8) lib/enum.ex:4830: Enumerable.List.reduce/3
Function: &Keila.Mailings.deliver_campaign/1
    Args: ["nmc_2Br9XWL7"]
```
Could you please fix the timeout?
We have a dedicated 4 core server with 16GB ram and want to send to ~36k recipients and it fails in that way.

**Comment by dompie** [comment]
No matter if I schedule or send by using the UI.

**Comment by dompie** [comment]
It's also impossible now to stop the campaign, because it was once scheduled and I get the following error when trying to stop:

![Screenshot 2024-07-09 at 11-13-53 Open Source Newsletter Tool · Keila](https://github.com/pentacent/keila/assets/706491/26ce99c7-7a9e-4fc7-af83-1b84ea4ed244)

**Comment by wmnnd** [comment]
36k recipients isn’t actually that many, so I’m surprised you’re encountering this issue. In this step of the delivery, the campaign isn’t yet processed, only the recipient structs and delivery jobs are inserted.

**Comment by wmnnd** [comment]
I’ve just pushed an update with an increased timeout of 60 seconds. Does that work for you?

**Comment by dompie** [comment]
We have in total about 500k recipients and I have about 3 rules on the segment to match custom data. I noticed earlier that segments on custom data are horribly slow. Will check timeout as soon as build finishes.

**Comment by dompie** [comment]
It's sending now...but load should be optimized imho for sending ~36k recipients. I have limited sending to 180/minute and 6000/hour.

![load2](https://github.com/pentacent/keila/assets/706491/4f22ba00-5915-4a7b-bcbb-7309ddccec64)

**Comment by dompie** [comment]
Thank you very much for fast fix :+1:
