### ISSUE TITLE
Switch MAILER_SMTP_USER and MAILER_SMTP_FROM_EMAIL defaults

### ISSUE THREAD

**Issue by abelcst** [pentacent/keila#320]
iex(keila@9dcd58287f1c)1> Keila.Auth.create_user(%{email: "abel.j@cybersapient.io", password: "Bladerunner098"})
** (MatchError) no match of right hand side value: {:error, {1, :smtp_rfc5322_parse, [~c"syntax error before: ", ~c"'>'"]}}
    (gen_smtp 1.2.0) /deps/gen_smtp/src/mimemail.erl:999: :mimemail.encode_header_value/2
    (gen_smtp 1.2.0) /deps/gen_smtp/src/mimemail.erl:963: :mimemail.encode_headers/1
    (gen_smtp 1.2.0) /deps/gen_smtp/src/mimemail.erl:964: :mimemail.encode_headers/1
    (gen_smtp 1.2.0) /deps/gen_smtp/src/mimemail.erl:210: :mimemail.encode/2
    (swoosh 1.11.6) lib/swoosh/adapters/smtp.ex:56: Swoosh.Adapters.SMTP.deliver/2
    (keila 0.14.11) lib/keila/mailer.ex:2: anonymous fn/2 in Keila.Mailer.instrument/3
    (telemetry 0.4.3) /deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    iex:1: (file)
iex(keila@9dcd58287f1c)1>

**Comment by wmnnd** [comment]
It sounds like there was an issue with your system sender. Were you able to resolve the problem in the meantime?

**Comment by rhodrid** [comment]
I had exactly the same issue. I tried tweaking a few env vars like smtp port and ssl settings. Then I realised that it was because I didn't have MAILER_SMTP_FROM_EMAIL set as it defaults to MAILER_SMTP_USER which, in my providers case, is not an email address. Setting MAILER_SMTP_FROM_EMAIL to an email address fixed the error.

**Comment by wmnnd** [comment]
Thanks for sharing this! Maybe I’ll switch the default behavior around in a future version so that `MAILER_SMTP_FROM_EMAIL` has to be set and if `MAILER_SMTP_USER` is not set, it defaults to the from address.

**Comment by wmnnd** [comment]
Closing this in favor of #356
