### ISSUE TITLE
API page for contacts

### ISSUE THREAD

**Issue by Marthaarman** [pentacent/keila#325]
Hi, 

I'm trying to make  a GET request for the contacts in the api but I only seem to be able to get the first page.

When I make the request like this in postman:
![image](https://github.com/user-attachments/assets/ff16014f-7eda-476c-a479-81e6c96fecdf)

The result down below is:
![image](https://github.com/user-attachments/assets/3610912e-a96e-44c7-83bc-1ae0676cc5a5)

Or should I add these parameters to the URL? But then, how? I cannot figure it out using the documentation for some reason. 
Their example says:
`https://mysite.com/api/v1/contacts?paginate%5Bpage%5D=0&paginate%5Bpage_size%5D=500` and fails itself when executed

**Comment by wmnnd** [comment]
`https://app.keila.io/api/v1/contacts?paginate%5Bpage%5D=0&paginate%5Bpage_size%5D=500` should work without any issues as described in the API docs. When you say the query `fails`, what exactly do you mean? Is there an error? Do you see anything in your Keila logs?

**Comment by Marthaarman** [comment]
I'm sorry I didn't probe the query correctly. 

I think, though, that the documentation should be clarified a bit though. 
What essentially happens is that the url now becomes:
https://mysite.com/api/v1/contacts?paginate[page]=0&paginate[page_size]=500

It is there, but the %5b and %5d make it less clear, and can only be found when you run an example. 

A bit of nitpicking though because it toke me a while to notice. Thanks anyway for your response.
