### ISSUE TITLE
Removing Shared senders

### ISSUE THREAD

**Issue by bpivk** [pentacent/keila#326]
My coworker has entered some shared senders for testing and now they can't be removed.
Logs show no errors when deleting. 

How can I remove them?

**Comment by wmnnd** [comment]
What happens when you try to delete a shared sender?

**Comment by bpivk** [comment]
Nothing. It just doesn't do it and the logs show nothing.

**Comment by wmnnd** [comment]
Ah, interesting! I can confirm deleting shared senders is currently not working. I’ll have a fix ready for this soon.
