### ISSUE TITLE
Required Checkbox in Sign-Up Form is'nt working

### ISSUE THREAD

**Issue by cyberwuulf** [pentacent/keila#328]
When setting up a sign-up form, there are custom field options. Using the required checkbox is not working with a custom checkbox.
Expected behaviour:
When using a custom field with the "checkbox" option and the "required"-option is set, the form should not be accepted if the checkbox is not ticked and a warning should be showed to the user.
Actual behaviour:
The form got submitted and the double-opt-in-e-mail got send.
When accessing the new contact in the contacts area, it shows in the json under Data like that:
"custom-field": false

I tested the same field with just "text" and it worked correctly, the form was not

**Comment by wmnnd** [comment]
Thanks for reporting this! I can confirm this is currently not working as expected.

**Comment by cyberwuulf** [comment]
Thank you, for your fast response and the even faster fix.
