### ISSUE TITLE
RFE : Add details about bounces and complaints in Campaign reports

### ISSUE THREAD

**Issue by MagicFab** [pentacent/keila#330]
I've noticed the campaign reports include stats about unsubscribes, bounces and complaints.

I can't seem to find details about such information. It would be very useful to know which recipients have bounced for example, to fix their contact information.

Somewhat related to #109.

I am also wondering how are "complaints" received / accounted for.

**Comment by wmnnd** [comment]
Thank you for suggesting this! I think #109 already covers this, so I’ll close this in favor of that issue and add a note there that complaints should also be added.

To answer your question about how complaints are received: On Keila Cloud (or if you have set up SES with a feedback webhook), Keila can receive complaint notifications from ISPs. These notifications are usually sent when a user manually marks an email as unwanted/spam.
