### ISSUE TITLE
Client's are Missing Out on Dozens of Deals a Week by Not Knowing Who Their Website Visitors Are. Create a Pixel to Solve This.

### ISSUE THREAD

**Issue by c2b247** [pentacent/keila#331]
Problem Statement:
Our clients are potentially missing out on numerous deals every week because they lack insights into who is visiting their websites. Understanding visitor profiles can significantly enhance targeted outreach and conversion rates.

Proposed Solution:
Develop a pixel that can be embedded into clients' websites. This pixel will track and identify visitors by linking their activity to profiles such as LinkedIn or email addresses. Once identified, these visitors should be automatically pushed into a pre-defined outreach campaign within Keila.

Implementation Steps:
Pixel Development: Create a lightweight tracking pixel that clients can easily integrate into their websites.
Visitor Identification: Implement mechanisms to identify visitors using available data (e.g., LinkedIn, email).
Automated Campaign Integration: Set up a system to automatically add identified visitors to a specific outreach campaign within Keila.
Privacy and Compliance: Ensure that all tracking and data collection complies with relevant privacy laws and regulations (e.g., GDPR).

Benefits:
Enhanced lead generation by capturing potential clients who visit the website.
Automated workflow reduces manual effort in identifying and adding leads to campaigns.
Increased conversion rates through targeted and timely outreach.

Additional Notes:
Consider providing clients with analytics and insights on visitor behavior and campaign performance.
Ensure that the pixel is customizable to fit various client needs and website platforms.

**Comment by wmnnd** [comment]
Hey there, thank you for your suggestion.

The goal of the Keila project is to provide a great email newsletter tool, not to be an advanced user tracking/website analytics tool. If you want to track users on your website, you need to use a different tool and if you want to use data from user tracking in your Keila campaigns, you can easily achieve this by using the Keila API.
