### ISSUE TITLE
How to use Keila with proxy?

### ISSUE THREAD

**Issue by satoshinotdead** [pentacent/keila#333]
Following #213, I open this issue to discuss about how to use Keila behind a proxy as Nginx. I've attempted to run Keila on our servers three times, but it hasn't worked.

The following configuration results in wss errors in the browser console:

```
        location / {
                proxy_pass http://127.0.0.1:4000;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $http_host;
        }
```

```
URL_HOST=mail.domain.tld
```

**A working template would be greatly apprecited.**

**Comment by wmnnd** [comment]
These nginx settings look like they should work, but without further details on what exactly isn’t working I can’t really help here. Feel free to reopen with more details!

**Comment by partofthething** [comment]
FWIW these apache reverse proxy settings do work:

```
ProxyPass / http://127.0.0.1:4000/
ProxyPassReverse / http://127.0.0.1:4000/
SSLCertificateFile /etc/letsencrypt/live/site.tld/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/site.tld/privkey.pem

# WebSocket proxy
RewriteEngine On
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule /(.*) ws://127.0.0.1:4000/$1 [P,L]

```

**Comment by BloodyIron** [comment]
For those who are interested in using NGINX as a Reverse-Proxy in-front of Keila (served by another system) I have posted details in another thread, in addition to a Kubernetes NGINX Ingress example (multiple comments in the thread I'm going to link to)

Here -> https://github.com/pentacent/keila/issues/385#issuecomment-2662077361
