### ISSUE TITLE
[Proposal] Bounties support for community development?

### ISSUE THREAD

**Issue by zcesur** [pentacent/keila#335]
Hey y'all! :wave: I found Keila on GitHub Trending in Elixir monthly. I'm the creator of Algora an open source bounties & livestreaming platform. We use bounties ourselves for building Algora.tv also in Elixir, they look like this:

  <p align="center">
    <a href="https://console.algora.io/org/algora/bounties?status=open">
      <img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2Falgora%2Fbounties%3Fstatus%3Dopen" alt="Open Bounties">
    </a>
    <a href="https://console.algora.io/org/algora/bounties?status=completed">
      <img src="https://img.shields.io/endpoint?url=https%3A%2F%2Fconsole.algora.io%2Fapi%2Fshields%2Falgora%2Fbounties%3Fstatus%3Dcompleted" alt="Rewarded Bounties">
    </a>
  </p>
</p>

Bounties are rewards on issues that are paid when PRs are merged. 
Both community members & maintainers can create bounties. 
Is this something you've tried before? Have you considered it?

Pardon me for the 'cold' intro & feel free to close this issue if this doesn't resonate.
I wanted to make myself available in case this is a utility that can help Keila users :)

**Comment by wmnnd** [comment]
Hey, thanks for this suggestion! I will definitely keep it in mind for the future but since I don’t think we’ll add this very soon, I’ll close it for now. Good luck with your project! 😊
