### ISSUE TITLE
Max characters in name field to stop spam

### ISSUE THREAD

**Issue by Lislegaard** [pentacent/keila#342]
To keep signup simple I do not have any double confirm setup. This leads to a few spam-subscriptions here and there. They all put in first names like "buy bitcoin on telegram number aspdofjasdpfoj" and some emojies etc.

How about giving people an error if they have more than 4 words or max amount of characters or something to block these signups?

**Comment by wmnnd** [comment]
Good idea! I’ve implemented this now in 03e81da3bbc11cd6fcc9367e6700cd1c4a919e77, limiting the length of the `first_name` and `last_name` fields to 50 characters.

**Comment by Lislegaard** [comment]
Hey,

I just wanted to say that after this I have not had any problems with fake signups.

Best,
Kristoffer



–––––––––––––––––––––––––––––
Kristoffer Lislegaard

Your friendly experimental ambient musician
kristofferlislegaard.com <https://www.kristofferlislegaard.com/>

— Follow <https://www.kristofferlislegaard.com/follow/> my newsletter
— Listen <https://kristofferlislegaard.com/listen> to my music
— Read <https://lisleg.com/blog> my blog
–––––––––––––––––––––––––––––

**Comment by wmnnd** [comment]
Thanks for reporting this!
