### ISSUE TITLE
Feature suggestion: header sections in templates

### ISSUE THREAD

**Issue by bovender** [pentacent/keila#343]
In templates, it would be great (IMHO) to be able to define a header section, similar to the footer/signature section.

This would allow users to use e.g. logos or banners in a consistent way across campaigns.

**Comment by wmnnd** [comment]
Thank you for this suggestion, @bovender! I’m currently planning to completely rework the template system. With the flexibility of the new system, it will be possible to define headers as well as footers. This is why I will close this issue in favor of #355.
