### ISSUE TITLE
Loosing all data after container restart

### ISSUE THREAD

**Issue by deraljoscha** [pentacent/keila#345]
I've been using Keila for a few days and was super happy about everything.
But today after restarting the container all data was lost, even though I didn't change enything about my docker compose file
Can anyone help?

this is my docker compose

version: "3"

services:
  keila:
    image: pentacent/keila:latest
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    build:
      context: ../
      dockerfile: ops/Dockerfile
    environment:
      SECRET_KEY_BASE: secretsecret
      DB_URL: "postgres://postgres:postgres@postgres/postgres"
      URL_HOST: mydomain.com
      #URL_SCHEMA: 'https'
      #URL_PORT: '443'
      KEILA_USER: my@mail.com
      KEILA_PASSWORD: mypassword
      MAILER_SMTP_HOST: mysmtp
      MAILER_SMTP_USER: username
      MAILER_SMTP_PASSWORD: 'password'
      DISABLE_REGISTRATION: true

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

**Comment by deraljoscha** [comment]
thanks for your quick answer
but no i wasnt talking about the pictures, I know i didnt set a store for that.
my whole project was gone, with templates, campaigns, contacts etc

**Comment by wmnnd** [comment]
In that case something is most likely wrong with your Postgres container. Maybe you also didn't set a volume for that and it was recreated as well?
