### ISSUE TITLE
Subscription Cancelation and re-subscribe automation.

### ISSUE THREAD

**Issue by azamaziz989** [pentacent/keila#347]
I think that this method will be an enhancement.

  @doc """
  Cancels `Subscription` with given `id`. In order to remain consistent with the
  Paddle API, this sets the `Subscription`’s `status` attribute to `:deleted`.
  """
  @spec cancel_subscription(Subscription.id()) ::
          {:ok, Subscription.t()} | {:error, Changeset.t(Subscription.t())}
  def cancel_subscription(account_id) do
    account_id
    |> get_subscription()
    |> Repo.delete()
  end

This function in the billing.ex will delete the whole subscription as soon as a user cancels a subscription. The user will come to the same point as if he has created a new account and can subscribe again. This will automate the subscription setup and will give the user full control over his subscription.

Please have a look.

**Comment by wmnnd** [comment]
Thank you for this suggestion! However, subscriptions and the billing system are not supported for self-hosted instances, so I’ll close this issue.
