### ISSUE TITLE
Email Client Integration.

### ISSUE THREAD

**Issue by azamaziz989** [pentacent/keila#351]
Hi. I thing it would a enhancement to add the option to compose single emails. Like adding roundube in it. It would be also better to have inbox but I thing that would be more difficult. But I think it would be easy to add the option to compose emails with the sent emails history as roundcube does. 
Please share your thoughts.

**Comment by wmnnd** [comment]
Hey there, thanks for sharing this idea! It's currently not possible to send emails to individual recipients with Keila but it will be possible once #355 and #344 are implemented. However, a sending experience like in Roundcube is not really part of the roadmap for Keila. If you want something like that, it's probably best to use Roundcube directly :-)
