### ISSUE TITLE
WYSIWYG HTML editor

### ISSUE THREAD

**Issue by Korne127** [pentacent/keila#352]
I found this project and tried it out, and I really like the way it works, the nice GUI and the ease of use, e.g. compared to alternatives like phplist.
However, there is one missing feature which basically makes this a non-option for me: The editors are all Markdown-based. While this may be suitable for some people, it is not just unusual but also has severe limitations, most of all not being able to change the font size.
While technically a HTML editor exists, it's not really usable for non-developers and people who just want to write an email.
I would expect such a tool to have a WYSIWYG / GUI HTML editor like e.g. phplist or mail websites:
<img width="789" alt="image" src="https://github.com/user-attachments/assets/96b53887-318a-4019-8d1d-5bebdf96d636">

**Comment by wmnnd** [comment]
Thank you for your suggestion! Keila already has two non-Markdown based options:

1) You can use the WYSIWYG block editor
2) You can use the MJML editor for full control over your template

I’m currently working on a new visual editor that allows you to leverage all the features of MJML for creating responsive emails. I posted a little sneak-peak of the development progress a while ago here: https://fosstodon.org/@keila/113033520717866406

**Comment by Korne127** [comment]
> You can use the WYSIWYG block editor

The block editor is just a WYSIWYG Markdown editor. And yes, while it may be a good thing to use Markdone for some use cases, it definitely lacks most of the flexibility and many features that are often important, especially font sizes.

> You can use the MJML editor for full control over your template

I referenced this editor in my original post: "While technically a HTML editor exists, it's not really usable for non-developers and people who just want to write an email. I would expect such a tool to have a WYSIWYG / GUI HTML editor like e.g. phplist or mail websites."


As I wrote in my original post, there is no option for a WYSIWYG no-Markdown / HTML editor, which I'd consider essential for any such service, especially considering that this is the type of editor basically everyone uses in any email program and therefore expects to use when sending emails.
As far as I know, there are quite some projects that basically provide exactly this (a WYSIWYG HTML editor) which could be integrated.

**Comment by wmnnd** [comment]
> The block editor is just a WYSIWYG Markdown editor. And yes, while it may be a good thing to use Markdone for some use cases, it definitely lacks most of the flexibility and many features that are often important, especially font sizes.

Nope, the block editor is not a WYSIWYG Markdown editor. Maybe you’re confusing it with the WYSIWYG Markdown editor which Keila also has?

Here’s a screenshot of the Block Editor with a multi-column layout, something that wouldn’t be possible using Markdown 😊 

![sos](https://www.keila.io/_astro/block-editor.BlyU0WG3_1wQgsS.webp)

You can read more about the block editor in the release announcement from last year: https://www.keila.io/updates/block-editor

**Comment by Korne127** [comment]
Okay interesting; I tried the editor again, and apparently I missed that. It seem like it's a Markdown + multi column (+ button) editor. That's really interesting as I haven't seen such a thing before, but it's still essentially Markdown, just with an additional feature.
My point wasn't that it's exactly Markdown, but that it's generally very limited and that a standard **HTML** editor is more (or at least as) important, not just because it gives more options and is the type of editor that basically every mail program uses and that basically everyone is used to, but also because it's the underlying format that's actually used and sent in the e-mail.

**Comment by wmnnd** [comment]
That’s why we’re working on adding an MJML WYSIWYG editor 😄 
Unfortunately, an off-the-shelf HTML editor won’t do because the HTML supported by email clients is extremely limited and inconsistent. Because of that we’ll be using MJML as an intermediary layer.

Are you currently missing a specific feature from the Block Editor?

**Comment by Korne127** [comment]
> That’s why we’re working on adding an MJML WYSIWYG editor 😄

Yes, that's a solution to what I proposed :D
I was mostly referring to the other editors as you closed this issue as completed (when imo it's not completed as the current options don't solve this).

> the HTML supported by email clients is extremely limited and inconsistent

Ah, that's good to know. I haven't thought about that before. Sadly, this seems plausible, although it makes me wonder as many emails are basically websites / use more advanced features.
The HTML editor I knew of / had in my mind was [CKEditor](https://ckeditor.com), which is used by phplist. I'll assume there are open source alternatives that provide HTML editing for mails. But I don't think it's anything bad to develop your own editor for that, especially if it's customized to your needs and based on the infrastructure.

I think as long as it supports the mainstream options that most email clients also provide (different fonts, sizes, (background) colours, strike-through, centering, indentation) and is similar to use (see the screenshot I send earlier or below), it's fine :)

<img width="548" alt="image" src="https://github.com/user-attachments/assets/a2a26d93-6ffd-440c-8146-64400bc30a15">

<img width="637" alt="image" src="https://github.com/user-attachments/assets/42b00c1d-a3e1-4a02-b922-15ad0a4ba2d6">

Thank you for your work on this project in any case, I appreciate it. :)
