### ISSUE TITLE
'emails opened' is not being tacked/reflected in both 'Campaign Stats' & 'Contact Activities'

### ISSUE THREAD

**Issue by K-J-VV** [pentacent/keila#354]
Just setup instance using an SMTP provider and I am able to create & send campaigns without a problem. However the tracking does not seem entirely accurate

When I send a test campaign to myself I click the email open but the Campaign Stats do not show this. Even when I mark the email as Unread to then re-Read it, there is no update.

However, if I click a link within the Campaign email then in Campaign Stats both the 'emails opened' and 'emails clicked' track this change as +1.

When I click into the contact profile I am able to see similar statistics to what I describe above

**Comment by wmnnd** [comment]
Hey there, thank you for reporting this.

What you're describing is a technical limitation in how email open tracking works in Keila and all other email tools. Keila includes an image in the email and when that image is loaded, it's assumed that the recipient has opened the email.
So if you're sending a plain text campaign or if your email client blocks the loading of external images, the "read" state in Keila will not be updated.
