### ISSUE TITLE
Switch MAILER_SMTP_FROM_EMAIL and MAILER_SMTP_USER defaults

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#356]
Currently, only `MAILER_SMTP_USER` needs to be set. If it's set, `MAILER_SMTP_FROM_EMAIL` defaults to the value of `MAILER_SMTP_USER`. This logic should be reversed to avoid issues where the SMTP user is not an email address or considered private.

**Comment by kevinam99** [comment]
Hey @wmnnd. I decided to take this up and opened the PR for it here https://github.com/pentacent/keila/pull/358

**Comment by kevinam99** [comment]
Just a nudge to close this issue
