### ISSUE TITLE
Campaigns Stuck in 'Being Sent' Status

### ISSUE THREAD

**Issue by lexoyo** [pentacent/keila#357]
Hello

I'm using docker image `pentacent/keila:0.15.0` and I have a weird thing happening recently, maybe since I migrated from `pentacent/keila:0.12.6`

My campaigns are not really processed, they stay `This campaign is currently being sent out.`

The logs show only one strange error

```
[error] GenServer :tzdata_release_updater terminating
** (ArgumentError) errors were found at the given arguments:
```

My campaigns my have been configured with different time zone as I travel all the time

Would you know how to get my 2 campaigns to send ?

**Comment by wmnnd** [comment]
0.15.0 is not the latest version. Could you try 0.15.1?

**Comment by lexoyo** [comment]
Thank you so much for the quick answer ! 🙏
I'll test soon

**Comment by lexoyo** [comment]
I upgrade, it's still the same, I'll give it some time :)

**Comment by wmnnd** [comment]
You could take a look at what the job queue is doing. Either inspect  the`oban_jobs` table directly in Postgres or check in the Keila console via `Keila.Repo.all(Oban.Job)` to check if something seems to be erroring. Are you sure your sender is configured correctly?

**Comment by wmnnd** [comment]
I’m going to close this for now, but if you have more data or discovered a solution, please feel free to reopen this issue!
