### ISSUE TITLE
Image & File Uploads

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#38]
Right now, Keila has no way of including files or images with emails.

Before we start working on this, I think we should clarify the following questions:

1. Do we want to support inlining images and email attachments?
2. Which types of storage should be supported?
3. Should Keila support bring-your-own-storage?
4. Should Keila support processing (i.e. cropping/resizing) images?
5. Can we rely on available libraries to do some of the heavy-lifting?

And finally: Even if the answer to all of the above questions is Yes: Which of these are absolutely necessary for version 1.0?

**Comment by wmnnd** [comment]
So my thinking is this:

1. No support for attachments and inlined images for 1.0.
2. Local file storage and maybe S3.
3. I don’t think it’s necessary to support bring-your-own-storage like we do for email senders. So one global storage configuration per instance should be enough.
4. I don’t see that as part of the MVP; it’s probably something we could add later once the templating system has a concept of "images".
5. I created a library called [Belt](https://hexdocs.pm/belt/Belt.html) to take care of sending files to different types of storage and to store the necessary information in the database. I created it almost four years ago, so I would certainly do some things differently now. But I do have it running in a production environment and it’s working quite well. On the other hand, if we were to support only local storage, we might not need something like this at all. I’m also open to consider alternative solutions or building something for Keila specifically.

I’d be very happy to hear some more thoughts :smile:

**Comment by wmnnd** [comment]
P.S.: Maybe image resizing could also be handled client-side. It might be an option because with our default Markdown template, images wider than 600px make no sense.

**Comment by cb3inco** [comment]
1. I think both attach and inline would be ideal
2. local and s3-compatible would be ideal - something configurable by the admin and its a either or option.
3.
4. Possibly basic editing or at least a warning if it's over a recommended size and the user can resize locally if needed.
5.

**Comment by wmnnd** [comment]
This is how the first version of this feature will be implemented:

- Local storage only
- Support for resizing via imagemagick
- No cid or base64 support for the first version

**Comment by wmnnd** [comment]
Implemented in #139.
