### ISSUE TITLE
Usability, Password Input fields

### ISSUE THREAD

**Issue by Jcambass** [pentacent/keila#4]
Some sender configurations use `password_input`, while this is good for security it makes it harder for users to understand if they have set a value or not.
![image](https://user-images.githubusercontent.com/3436381/107791714-8d493e00-6d54-11eb-9fb7-b0b7bb3b9e0a.png)

This together with the fact that one can set values in multiple tabs at the same time makes it hard for users to understand which config they have configured and which one is now actually active (separate issue):

Maybe we should consider rendering some placeholders like `*****` when a value is set in the password fields. Or if we really want we could display the actual values stored in the database, this would also make it easier for users to ensure that they have configured the correct value without just resetting it.

**Comment by wmnnd** [comment]
I agree it’s not quite ideal to present a blank field. But I would prefer not to expose the credentials once they’ve been entered into the system.

Maybe one solution could be to make the password fields optional when viewing/editing a `Sender` and requiring a checkbox for enabling them (Something like `[X] Change API Key`). What do you think?

**Comment by Jcambass** [comment]
Jup I think we need something where the user explicitly says "ok I know this value is already set but let me reset it". This could also be an inline edit button in the field with an information tooltip or something along those lines.

This would cover both issues:
- Knowing that a value is set.
- Allowing to open the edit form without resetting the value directly.

One thing that it doesn't solve is the fact that the user might not understand that the current tab will be the type used. I'm not really sure how we can communicate that without making things complicated. Another thing that would be nice just from a data perspective would be to clear the values of the not chosen sender types upon save.

I'm not the biggest UI guru, so that's why I can't really offer any wireframes or mockups at this point 😄.
