### ISSUE TITLE
Campaign Editor shows different Font than defined in Template

### ISSUE THREAD

**Issue by Jcambass** [pentacent/keila#43]
During a very quick test of the template editor I noticed that the Campaign editor shows the wrong font uppon selecting a previously created template.

**Preview in Template Editor**

<img width="1035" alt="Screenshot 2021-03-31 at 19 55 34" src="https://user-images.githubusercontent.com/3436381/113189187-3394c880-925b-11eb-8685-caffa1b80ae0.png">

**Preview in Campaing Editor** 

<img width="1035" alt="Screenshot 2021-03-31 at 19 55 58" src="https://user-images.githubusercontent.com/3436381/113189175-31326e80-925b-11eb-9ba5-aba5deefae7a.png">

Opening the Campaign Editor in split view renders the font correctly:

<img width="1035" alt="Screenshot 2021-03-31 at 20 00 03" src="https://user-images.githubusercontent.com/3436381/113189615-b158d400-925b-11eb-90a4-204a9ec7129a.png">

**Comment by wmnnd** [comment]
It seems to be working fine here … could you share which font settings you chose and at which level (i.e. "Layout" vs "Content")?

![Screenshot_2021-03-31 Open Source Newsletter Tool · Keila](https://user-images.githubusercontent.com/7488303/113216084-1cb29e00-927c-11eb-8378-91d92a0bedcf.png)

**Comment by wmnnd** [comment]
@Jcambass Were you able to reproduce the issue?

**Comment by Jcambass** [comment]
@wmnnd I quickly checked again and wasn't able to reproduce it anymore. So very likely a local problem with my browser at the time. Feel free to close this :)

**Comment by wmnnd** [comment]
Thanks for giving it another look!
