### ISSUE TITLE
Make system email configurable

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#48]
Right now, `hello@keila.io` is used in some instances for sending system emails. This should be configurable via an environment variable instead.

**Comment by pascalwengerter** [comment]
Would you want to (re)use `MAILER_SMTP_USER` there or add a new, dedicated ENV var @wmnnd ?

**Comment by wmnnd** [comment]
Good question! I think for now just using that would be sufficient :smiley:

**Comment by wmnnd** [comment]
Implemented in #145.
