### ISSUE TITLE
Add User-Agent filtering to open tracking

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#55]
Some email providers, specifically Gmail, use bots to access links in emails. These can trigger false opens.
https://www.gmass.co/blog/false-opens-in-gmail/

Keila should recognize these bots and filter them out.

**Comment by panoramix360** [comment]
@wmnnd did you already manage to do that?

I'll have more time available for the next weeks and I'm thinking of getting this one.

And another thing, I'm not being able to edit campaigns, this error appears, maybe there is a new configuration that I need to do on Dev Container:
![image](https://user-images.githubusercontent.com/2154092/201556176-a066f605-7fdb-4945-9197-c1dd204b46ca.png)

**Comment by wmnnd** [comment]
@panoramix360 Nope, I haven’t been able to investigate this issue any further. If you’d like to give it a shot, that’d be great!

The error probably comes because the KeilaWeb.IconHelper module wasn’t recompiled after I added the `horizontal_rule` icon. If you make any modification to the module, save, then revert the change, the compiler should notice and it should work again.

**Comment by panoramix360** [comment]
@wmnnd sounds great!

I already implemented and will write some tests to open the PR :D

**Comment by wmnnd** [comment]
Implemented via #164 :partying_face:
