### ISSUE TITLE
[Feature] Support for MJML?

### ISSUE THREAD

**Issue by NoLooseEnds** [pentacent/keila#63]
Have you thought about adding support for [MJML template language?](https://github.com/mjmlio/mjml)

**Comment by wmnnd** [comment]
I think adding MJML support would certainly be an interesting idea. Do you know of any good FLOSS WYSIWYG editors for MJML?

**Comment by NoLooseEnds** [comment]
No, sorry. I don't know about any that let you edit in WYSIWYG on the fly. 

All I've encountered is coding in mjml and providing a live preview, but I have not used it that much – but it was a very good experience when I did.

Maybe open an issue with mjml? 

I found this: https://github.com/artf/grapesjs-mjml – not sure if you get anything from it.

**Comment by wmnnd** [comment]
There are currently no immediate plans for adding MJML to Keila, so I’ll be closing this for now.
