### ISSUE TITLE
Get notifications for people that unsubscribed

### ISSUE THREAD

**Issue by Vinnpinn** [pentacent/keila#68]
There should be some sort of info if a user unsubscribes. The current way only works well if they've signed themselves up for a newsletter. With no information if someone has unsubscribed from the newsletter it's a lot of work to filter them out if you have the same contact in multiple campaigns or if you want to mark that person as "no newsletter" in your customer database that lives outside of keila.

Hope I followed you issue guidelines, really enjoying keila so far ;-)

**Comment by wmnnd** [comment]
Hey, thanks for giving Keila a try and for your suggestion!

I’ve actually been thinking about how to solve this issue. As you say, it’s specifically a problem when you have a list of contacts that you want to import and you want to avoid re-adding someone who has unsubscribed.

So what I’m planning to do now is this: When a contact unsubscribes, their email is still deleted from the database, but a hash of the email is retained. Like this, Keila will be able to filter out existing unsubscribed contacts when doing an import.

Would that solve the problem you were having?

**Comment by Vinnpinn** [comment]
Hey, thank's for the reply. This would solve part of the issue and would probably work fine if one only ever used Keila and would never switch to something else or only collected e-mail adresses through keila.
However if anyone ever decided to switch to a diffrent system the would have issues with knowing who unsubscribed from newsletters. If you collect your E-Mail adresses from outside keila, e.g. using your existing customer database I don't see how it's possible to keep track of who want to recieve newsletters and who doesn't. 
What I was thinking was maybe a page with everyone that unsubscribed and you could then tick them for deletion. So that you can manually check those email adresses and mark them "no newsletter" on your customer database before deleting them.

**Comment by wmnnd** [comment]
There is now a PR addressing this, #69
