### ISSUE TITLE
Docker-Compose deployment fails with ERROR: Unknown command /bin/sh

### ISSUE THREAD

**Issue by cb3inco** [pentacent/keila#71]
Using the example in the ops folder using the docker-compose.yml file, when trying to start the Keila container, I get the following error:

``` 
postgres is up-to-date
Starting keila ... 
Starting keila ... done
Attaching to keila
keila             | Usage: keila COMMAND [ARGS]
keila             | 
keila             | The known commands are:
keila             | 
keila             |     start          Starts the system
keila             |     start_iex      Starts the system with IEx attached
keila             |     daemon         Starts the system as a daemon
keila             |     daemon_iex     Starts the system as a daemon with IEx attached
keila             |     eval "EXPR"    Executes the given expression on a new, non-booted system
keila             |     rpc "EXPR"     Executes the given expression remotely on the running system
keila             |     remote         Connects to the running system via a remote shell
keila             |     restart        Restarts the running system via a remote command
keila             |     stop           Stops the running system via a remote command
keila             |     pid            Prints the operating system PID of the running system via a remote command
keila             |     version        Prints the release name and version to be booted
keila             | 
keila             | ERROR: Unknown command /bin/sh
keila exited with code 1
````

My docker-compose looks like this:

```
#Keila
  keila:
    image: pentacent/keila:latest
    container_name: keila
    ports:
      - "4000:4000"
    depends_on:
      - postgres
#    build:
#      context: ../
#      dockerfile: ops/Dockerfile
    environment:
      SECRET_KEY_BASE: "[REDACTED]"
      DB_URL: "postgres://postgres:postgres@postgres/postgres"
      URL_HOST: "keila.domain.com"
      MAILER_SMTP_HOST: "smtp.emailserver.com"
      MAILER_SMTP_USER: "user@domains.com"
      MAILER_SMTP_PASSWORD: "[REDACTED]"

  postgres:
    image: postgres:alpine
    container_name: postgres
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

```
This is similar to this issue I think - https://github.com/pentacent/keila/issues/64 - what other details can I provide?

Note: Not actual key or smtp password.

**Comment by wmnnd** [comment]
Is it possible you still have an outdated image in your Docker cache? Could you try running `docker-compose pull`?

**Comment by cb3inco** [comment]
```
Pulling keila (pentacent/keila:latest)...
latest: Pulling from pentacent/keila
Digest: sha256:b70a7db149d68acbcfec63cc2c5ae4469ca89afe6036a7ecb5219f0ceba4e55c
Status: Image is up to date for pentacent/keila:latest
```

Did a pull and this is what I get.

**Comment by cb3inco** [comment]
I also just used ``` docker image rm b70a7db149d6 ``` and re-pulled it. No change.

**Comment by cb3inco** [comment]
Sorry another update. I ended up cloning the repo to my local linux box, and tried to build the container locally (never pulled the image from Docker Hub). It builds and runs as I would expect it. If I remove all images from my machine and then pull from Docker Hub, it results in the same issue listed above ```keila             | ERROR: Unknown command /bin/sh
keila exited with code 1 ``` - it would seem there is an issue with the build to Docker Hub.

**Comment by cb3inco** [comment]
Sorry I keep digging. It seems that per the issue #64 that you fixed the problem in v0.5.4, but when I review your github actions the build on Jul 8th failed for that version. So the broken version is still the 'latest' - v0.5.3. And there is no release listed for v0.5.4, though the repo has the correct fix, which is why it builds local.

https://github.com/pentacent/keila/actions/runs/1011300983 - the user of issue #64 may have never followed up to test this and report it is my guess.

**Comment by wmnnd** [comment]
You’re right, and I didn’t notice because I had manually tagged the image on my local machine. I think the error in the workflow was simply some incorrect quotes which should be fixed now. I’ll prepare a new release soon :smiley:

**Comment by wmnnd** [comment]
Thanks for looking into this, @cb3inco, the latest release should have fixed the issue :partying_face:

**Comment by cb3inco** [comment]
Works now! Thanks.
