### ISSUE TITLE
Feature Requests and/or Questions

### ISSUE THREAD

**Issue by cb3inco** [pentacent/keila#72]
I've been playing with Keila and really like it's simplicity and distraction free interface over that of tools like Mailchimp. My use case for using this tool is to host a newsletter service for our staff to send emails out to donors who support our organization. Is there any plans for the following:

- Allow SAML authentication and automatic account provisioning. I'm sure others would love facebook/twitter/google sign up too.
- Administratively be able to set the email settings for a user so they don't have to
- Allow predefined templates for all users that are non-editable.
- Contact import from gmail, mailchimp, or other popular email services?
- Administratively see user of organization usage and status. 
- Automated import of contacts from a data object such as json or other per user (a import of donors that have given towards a specific person)
- Option to insert certain 'template tags' from the markdown editor and make is prettier for end user
- Preview button regardless of editor (right now in markdown, you have to view code editor, then hit preview button)
- Set a template as default
- Create separate lists of contacts or segments within a project
- Email/Webhook notice when a scheduled campaign is sent
- Ability to send a test email of a campaign
- Clone a template

I think that's all I got for now, but very excited about this project.

**Comment by wmnnd** [comment]
Hey there, thanks for your questions and suggestions!

I think there are some very good suggestions in your post, just too many of a single GitHub issue, really :wink: 

If you could open individual issues for the individual ideas, I think that would be very helpful!

To quickly address some of your points:

- Yep, I’m sure that would be nice, though it’s not necessarily a priority until 1.0 right now.
- With the new login-as feature, it’s already possible for admins to set email settings for users
- I think the template system could definitely use some improvements, such as the ability to edit the base HTML, create blocks, and globally available templates.
- What exactly do you mean by "usage and status"?
- If I understand this correctly, this would be possible once #75 is implemented.
- What exactly do you mean by "template tags"?
- Good point!
- Good point!
- Segmentation is definitely something we need for 1.0. I’ve just opened #83 for that. Feel free to comment there as well!
- Maybe this could be added as part of #75. But feel free to open a separate issue for it with more detailed specs.
- Good point!
- Cloning templates is already possible :smiley:

**Comment by wmnnd** [comment]
Since there was no further feedback on this issue, I’ll close it for now. Please feel free to re-open specific issues if you believe they’re still important.
