### ISSUE TITLE
[Feature Request] Support for base URL/subfolder reverse proxy

### ISSUE THREAD

**Issue by es9o** [pentacent/keila#77]
I'm currently able to successfully proxy my instance of Keila via keila.mydomain.com, but I'd love to have the ability to use a subfolder (app.mydomain.com/keila) instead.

Is this something that could be considered in a future release?

**Comment by pascalwengerter** [comment]
I'd like to give it a try, can't promise by when I can find the time though..

**Comment by wmnnd** [comment]
@es9o Could you give the branch in #78 a try?

**Comment by wmnnd** [comment]
This feature has now been merged and released in Keila 0.6.2!

**Comment by cinco** [comment]
hi guys,

the websocket URL is not considering the URL_PATH.

In the console I get `mydomain.com/live/websocket?_csrf_token=....`, even though I have `URL_PATH=/newsletter`. 

While you would expect the websocket at `mydomain.com/newsletter/live/websocket?_csrf_token=....`
