### ISSUE TITLE
Contact segmentation

### ISSUE THREAD

**Issue by wmnnd** [pentacent/keila#83]
It should be possible to segment users by contact fields as well as interaction data with previous campaigns.

**Comment by wmnnd** [comment]
- [ ] Add segment data entity
- [ ] Build UI for segment creation
- [ ] Allow sending campaigns to segments

**Comment by MagicFab** [comment]
A hidden field could be used to tie forms to projects/segments.

I've opened a request for this here; https://github.com/pentacent/keila/issues/140
