### ISSUE TITLE
Sending Campaings to 0 Contacts results in Stuck Progress

### ISSUE THREAD

**Issue by Jcambass** [pentacent/keila#9]
Currently, it's possible to send a campaign to 0 contacts. Doing this will result in the campaign being stuck in the `:preparing` stage forever.

![image](https://user-images.githubusercontent.com/3436381/108185003-1e7d3380-710c-11eb-9060-b1fa78dcf7de.png)

**Comment by wmnnd** [comment]
Thanks for reporting this! I’ll fix it right away, then we should be ready to go for the 0.1.0 release.
