### ISSUE TITLE
Add DevContainer support

### ISSUE THREAD

**Issue by panoramix360** [pentacent/keila#95]
I noticed that the project has a Dockerfile and docker-compose.yml, and was wondering if you guys know DevContainer from Microsoft?

Is a [tool](https://code.visualstudio.com/docs/remote/containers) to Visual Code that lets you develop inside a container, it's pretty neat.

To build/develop the project on my machine when contributing in the last PR I configured a devcontainer.json on the project to run it inside a container, it uses docker-compose by default.

Do you think that it'll be nice to have this configuration on the project? I can open a PR for this.

Thank you! :smiley:

**Comment by wmnnd** [comment]
I think that’s a neat idea to make developing Keila even easier! Feel free to create a PR, including a note in `README.md`.

I would just want to make sure it’s clear that this is an *optional* way of developing the project and not required :+1:

**Comment by panoramix360** [comment]
Glad that you liked it!

I agree with you about this being optional.

I'll create the PR and change the README to include how to configure this :tada:

**Comment by wmnnd** [comment]
This was implemented in #99 and is now part of the 0.9.0 release :partying_face:
